// Code generated by yunka contract; DO NOT EDIT.

package policy

import "yunka.io/gateway/authz"

const OperationAdvanceGate authz.OperationID = "delivery.items.advance-gate"
const OperationCloseItem authz.OperationID = "delivery.items.close"
const OperationCreateItem authz.OperationID = "delivery.items.create"
const OperationGetDashboard authz.OperationID = "delivery.dashboard.get"
const OperationListItems authz.OperationID = "delivery.items.list"
const OperationUpdateItemContext authz.OperationID = "delivery.items.update-context"

func Permissions() []authz.PermissionKey {
	return []authz.PermissionKey{"delivery.dashboard.read", "delivery.items.close", "delivery.items.gate", "delivery.items.read", "delivery.items.write"}
}

func Resolver() authz.StaticResolver {
	return authz.NewStaticResolver(map[string]authz.Policy{
		"/iot.delivery.v1.DeliveryService/AdvanceGate":       {Operation: OperationAdvanceGate, Permissions: []authz.PermissionKey{"delivery.items.gate"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
		"/iot.delivery.v1.DeliveryService/CloseItem":         {Operation: OperationCloseItem, Permissions: []authz.PermissionKey{"delivery.items.close"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
		"/iot.delivery.v1.DeliveryService/CreateItem":        {Operation: OperationCreateItem, Permissions: []authz.PermissionKey{"delivery.items.write"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
		"/iot.delivery.v1.DeliveryService/GetDashboard":      {Operation: OperationGetDashboard, Permissions: []authz.PermissionKey{"delivery.dashboard.read"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
		"/iot.delivery.v1.DeliveryService/ListItems":         {Operation: OperationListItems, Permissions: []authz.PermissionKey{"delivery.items.read"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
		"/iot.delivery.v1.DeliveryService/UpdateItemContext": {Operation: OperationUpdateItemContext, Permissions: []authz.PermissionKey{"delivery.items.write"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
	})
}
