// Code generated by yunka contract; DO NOT EDIT.

package policy

import "yunka.io/pkg/operationplan"

func OperationPlanAdvanceGate() operationplan.Plan {
	return operationplan.Plan{OperationID: "delivery.items.advance-gate", Domain: "delivery", Application: "management", UseCase: "advance_gate", RequestType: "iot.delivery.v1.AdvanceGateRequest", ResponseType: "iot.delivery.v1.WorkItemResponse", Execution: operationplan.Execution{Transaction: "local", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: false, Authentication: []string{"api-key", "jwt"}, Permissions: []string{"delivery.items.gate"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "local", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/iot.delivery.v1.DeliveryService/AdvanceGate", HTTP: []operationplan.HTTPBinding{}}}
}

func OperationPlanCloseItem() operationplan.Plan {
	return operationplan.Plan{OperationID: "delivery.items.close", Domain: "delivery", Application: "management", UseCase: "close_item", RequestType: "iot.delivery.v1.CloseItemRequest", ResponseType: "iot.delivery.v1.WorkItemResponse", Execution: operationplan.Execution{Transaction: "local", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: false, Authentication: []string{"api-key", "jwt"}, Permissions: []string{"delivery.items.close"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "local", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/iot.delivery.v1.DeliveryService/CloseItem", HTTP: []operationplan.HTTPBinding{}}}
}

func OperationPlanCreateItem() operationplan.Plan {
	return operationplan.Plan{OperationID: "delivery.items.create", Domain: "delivery", Application: "management", UseCase: "create_item", RequestType: "iot.delivery.v1.CreateItemRequest", ResponseType: "iot.delivery.v1.WorkItemResponse", Execution: operationplan.Execution{Transaction: "local", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: false, Authentication: []string{"api-key", "jwt"}, Permissions: []string{"delivery.items.write"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "local", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/iot.delivery.v1.DeliveryService/CreateItem", HTTP: []operationplan.HTTPBinding{}}}
}

func OperationPlanCreateItemComment() operationplan.Plan {
	return operationplan.Plan{OperationID: "delivery.items.comment.create", Domain: "delivery", Application: "management", UseCase: "add_comment", RequestType: "iot.delivery.v1.CreateItemCommentRequest", ResponseType: "iot.delivery.v1.CommentResponse", Execution: operationplan.Execution{Transaction: "local", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: false, Authentication: []string{"api-key", "jwt"}, Permissions: []string{"delivery.items.write"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "local", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/iot.delivery.v1.DeliveryService/CreateItemComment", HTTP: []operationplan.HTTPBinding{}}}
}

func OperationPlanCreateMilestone() operationplan.Plan {
	return operationplan.Plan{OperationID: "delivery.milestones.create", Domain: "delivery", Application: "management", UseCase: "create_milestone", RequestType: "iot.delivery.v1.CreateMilestoneRequest", ResponseType: "iot.delivery.v1.MilestoneResponse", Execution: operationplan.Execution{Transaction: "local", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: false, Authentication: []string{"api-key", "jwt"}, Permissions: []string{"delivery.items.write"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "local", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/iot.delivery.v1.DeliveryService/CreateMilestone", HTTP: []operationplan.HTTPBinding{}}}
}

func OperationPlanCreateProject() operationplan.Plan {
	return operationplan.Plan{OperationID: "delivery.projects.create", Domain: "delivery", Application: "management", UseCase: "create_project", RequestType: "iot.delivery.v1.CreateProjectRequest", ResponseType: "iot.delivery.v1.ProjectResponse", Execution: operationplan.Execution{Transaction: "local", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: false, Authentication: []string{"api-key", "jwt"}, Permissions: []string{"delivery.items.write"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "local", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/iot.delivery.v1.DeliveryService/CreateProject", HTTP: []operationplan.HTTPBinding{}}}
}

func OperationPlanCreateRelease() operationplan.Plan {
	return operationplan.Plan{OperationID: "delivery.releases.create", Domain: "delivery", Application: "management", UseCase: "create_release", RequestType: "iot.delivery.v1.CreateReleaseRequest", ResponseType: "iot.delivery.v1.ReleaseResponse", Execution: operationplan.Execution{Transaction: "local", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: false, Authentication: []string{"api-key", "jwt"}, Permissions: []string{"delivery.items.write"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "local", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/iot.delivery.v1.DeliveryService/CreateRelease", HTTP: []operationplan.HTTPBinding{}}}
}

func OperationPlanCreateSprint() operationplan.Plan {
	return operationplan.Plan{OperationID: "delivery.sprints.create", Domain: "delivery", Application: "management", UseCase: "create_sprint", RequestType: "iot.delivery.v1.CreateSprintRequest", ResponseType: "iot.delivery.v1.SprintResponse", Execution: operationplan.Execution{Transaction: "local", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: false, Authentication: []string{"api-key", "jwt"}, Permissions: []string{"delivery.items.write"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "local", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/iot.delivery.v1.DeliveryService/CreateSprint", HTTP: []operationplan.HTTPBinding{}}}
}

func OperationPlanGetDashboard() operationplan.Plan {
	return operationplan.Plan{OperationID: "delivery.dashboard.get", Domain: "delivery", Application: "management", UseCase: "get_dashboard", RequestType: "iot.delivery.v1.GetDashboardRequest", ResponseType: "iot.delivery.v1.GetDashboardResponse", Execution: operationplan.Execution{Transaction: "read_only", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: false, Authentication: []string{"api-key", "jwt"}, Permissions: []string{"delivery.dashboard.read"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "local", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/iot.delivery.v1.DeliveryService/GetDashboard", HTTP: []operationplan.HTTPBinding{}}}
}

func OperationPlanListItems() operationplan.Plan {
	return operationplan.Plan{OperationID: "delivery.items.list", Domain: "delivery", Application: "management", UseCase: "list_items", RequestType: "iot.delivery.v1.ListItemsRequest", ResponseType: "iot.delivery.v1.ListItemsResponse", Execution: operationplan.Execution{Transaction: "read_only", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: false, Authentication: []string{"api-key", "jwt"}, Permissions: []string{"delivery.items.read"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "local", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/iot.delivery.v1.DeliveryService/ListItems", HTTP: []operationplan.HTTPBinding{}}}
}

func OperationPlanUpdateItem() operationplan.Plan {
	return operationplan.Plan{OperationID: "delivery.items.update", Domain: "delivery", Application: "management", UseCase: "update_item", RequestType: "iot.delivery.v1.UpdateItemRequest", ResponseType: "iot.delivery.v1.WorkItemResponse", Execution: operationplan.Execution{Transaction: "local", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: false, Authentication: []string{"api-key", "jwt"}, Permissions: []string{"delivery.items.write"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "local", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/iot.delivery.v1.DeliveryService/UpdateItem", HTTP: []operationplan.HTTPBinding{}}}
}

func OperationPlanUpdateItemContext() operationplan.Plan {
	return operationplan.Plan{OperationID: "delivery.items.update-context", Domain: "delivery", Application: "management", UseCase: "update_item_context", RequestType: "iot.delivery.v1.UpdateItemContextRequest", ResponseType: "iot.delivery.v1.WorkItemResponse", Execution: operationplan.Execution{Transaction: "local", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: false, Authentication: []string{"api-key", "jwt"}, Permissions: []string{"delivery.items.write"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "local", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/iot.delivery.v1.DeliveryService/UpdateItemContext", HTTP: []operationplan.HTTPBinding{}}}
}
