// Code generated by yunka contract; DO NOT EDIT.

package policy

import "yunka.io/pkg/operationplan"

func OperationPlanAdvanceGate() operationplan.Plan {
	return operationplan.Plan{OperationID: "delivery.items.advance-gate", Domain: "delivery", Application: "management", UseCase: "advance_gate", RequestType: "iot.delivery.v1.AdvanceGateRequest", ResponseType: "iot.delivery.v1.WorkItemResponse", Execution: operationplan.Execution{Transaction: "local", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: false, Authentication: []string{"api-key"}, Permissions: []string{"delivery.items.gate"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "local", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/iot.delivery.v1.DeliveryService/AdvanceGate", HTTP: []operationplan.HTTPBinding{}}}
}

func OperationPlanCloseItem() operationplan.Plan {
	return operationplan.Plan{OperationID: "delivery.items.close", Domain: "delivery", Application: "management", UseCase: "close_item", RequestType: "iot.delivery.v1.CloseItemRequest", ResponseType: "iot.delivery.v1.WorkItemResponse", Execution: operationplan.Execution{Transaction: "local", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: false, Authentication: []string{"api-key"}, Permissions: []string{"delivery.items.close"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "local", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/iot.delivery.v1.DeliveryService/CloseItem", HTTP: []operationplan.HTTPBinding{}}}
}

func OperationPlanCreateItem() operationplan.Plan {
	return operationplan.Plan{OperationID: "delivery.items.create", Domain: "delivery", Application: "management", UseCase: "create_item", RequestType: "iot.delivery.v1.CreateItemRequest", ResponseType: "iot.delivery.v1.WorkItemResponse", Execution: operationplan.Execution{Transaction: "local", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: false, Authentication: []string{"api-key"}, Permissions: []string{"delivery.items.write"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "local", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/iot.delivery.v1.DeliveryService/CreateItem", HTTP: []operationplan.HTTPBinding{}}}
}

func OperationPlanGetDashboard() operationplan.Plan {
	return operationplan.Plan{OperationID: "delivery.dashboard.get", Domain: "delivery", Application: "management", UseCase: "get_dashboard", RequestType: "iot.delivery.v1.GetDashboardRequest", ResponseType: "iot.delivery.v1.GetDashboardResponse", Execution: operationplan.Execution{Transaction: "read_only", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: false, Authentication: []string{"api-key"}, Permissions: []string{"delivery.dashboard.read"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "local", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/iot.delivery.v1.DeliveryService/GetDashboard", HTTP: []operationplan.HTTPBinding{}}}
}

func OperationPlanListItems() operationplan.Plan {
	return operationplan.Plan{OperationID: "delivery.items.list", Domain: "delivery", Application: "management", UseCase: "list_items", RequestType: "iot.delivery.v1.ListItemsRequest", ResponseType: "iot.delivery.v1.ListItemsResponse", Execution: operationplan.Execution{Transaction: "read_only", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: false, Authentication: []string{"api-key"}, Permissions: []string{"delivery.items.read"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "local", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/iot.delivery.v1.DeliveryService/ListItems", HTTP: []operationplan.HTTPBinding{}}}
}

func OperationPlanUpdateItemContext() operationplan.Plan {
	return operationplan.Plan{OperationID: "delivery.items.update-context", Domain: "delivery", Application: "management", UseCase: "update_item_context", RequestType: "iot.delivery.v1.UpdateItemContextRequest", ResponseType: "iot.delivery.v1.WorkItemResponse", Execution: operationplan.Execution{Transaction: "local", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: false, Authentication: []string{"api-key"}, Permissions: []string{"delivery.items.write"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "local", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/iot.delivery.v1.DeliveryService/UpdateItemContext", HTTP: []operationplan.HTTPBinding{}}}
}
