// Code generated by yunka assembly compiler; DO NOT EDIT.

package assembly

import (
	"context"
	errors "errors"
	fmt "fmt"
	deliveryapplication "github.com/hvritual/iot-delivery-system/backend-yunka/internal/delivery/application"
	deliveryrpc "github.com/hvritual/iot-delivery-system/backend-yunka/internal/delivery/transport/rpc"
	deliveryruntime "github.com/hvritual/iot-delivery-system/backend-yunka/internal/deliveryruntime"
	localtx "github.com/hvritual/iot-delivery-system/backend-yunka/internal/localtx"
	"github.com/hvritual/yunka.io/framework/core"
	modulecatalog "github.com/hvritual/yunka.io/framework/core/modulecatalog"
	kernel "github.com/hvritual/yunka.io/framework/kernel"
	operation "github.com/hvritual/yunka.io/framework/operation"
	platform "github.com/hvritual/yunka.io/framework/platform"
	grpc "google.golang.org/grpc"
)

const AssemblyPlanDigest = "2b95d8fe42d237c651665803174dbc90c378b9b07c875b9ba35350017e4319a4"

type DeliveryManagementDependencies struct {
	DeliveryNotifications    deliveryruntime.Notifications
	DeliveryOutbox           deliveryruntime.Outbox
	DeliveryProjection       deliveryruntime.Projection
	SqliteTransactionFactory localtx.Factory
}

type ApplicationFactories interface {
	BuildDeliveryManagement(DeliveryManagementDependencies) (deliveryapplication.DeliveryService, error)
}

type Applications struct {
	DeliveryManagement deliveryapplication.DeliveryService
}

func BuildApplications(factories ApplicationFactories, executor operation.Executor) (Applications, error) {
	return BuildApplicationsWithCapabilities(factories, executor, modulecatalog.EmptyCapabilitySet())
}

func BuildApplicationsWithCapabilities(factories ApplicationFactories, executor operation.Executor, capabilities modulecatalog.CapabilitySet) (Applications, error) {
	if factories == nil {
		return Applications{}, errors.New("yunka assembly: application factories are required")
	}
	var applications Applications
	var err error
	deliveryManagementDeliveryNotificationsCapability, err := modulecatalog.ResolveCapability(capabilities, modulecatalog.MustCapabilityKey[deliveryruntime.Notifications]("delivery.notifications", "github.com/hvritual/iot-delivery-system/backend-yunka/internal/deliveryruntime", "Notifications"))
	if err != nil {
		return Applications{}, fmt.Errorf("yunka assembly: build delivery/management capability delivery.notifications: %w", err)
	}
	deliveryManagementDeliveryOutboxCapability, err := modulecatalog.ResolveCapability(capabilities, modulecatalog.MustCapabilityKey[deliveryruntime.Outbox]("delivery.outbox", "github.com/hvritual/iot-delivery-system/backend-yunka/internal/deliveryruntime", "Outbox"))
	if err != nil {
		return Applications{}, fmt.Errorf("yunka assembly: build delivery/management capability delivery.outbox: %w", err)
	}
	deliveryManagementDeliveryProjectionCapability, err := modulecatalog.ResolveCapability(capabilities, modulecatalog.MustCapabilityKey[deliveryruntime.Projection]("delivery.projection", "github.com/hvritual/iot-delivery-system/backend-yunka/internal/deliveryruntime", "Projection"))
	if err != nil {
		return Applications{}, fmt.Errorf("yunka assembly: build delivery/management capability delivery.projection: %w", err)
	}
	deliveryManagementSqliteTransactionFactoryCapability, err := modulecatalog.ResolveCapability(capabilities, modulecatalog.MustCapabilityKey[localtx.Factory]("sqlite.transaction-factory", "github.com/hvritual/iot-delivery-system/backend-yunka/internal/localtx", "Factory"))
	if err != nil {
		return Applications{}, fmt.Errorf("yunka assembly: build delivery/management capability sqlite.transaction-factory: %w", err)
	}
	applications.DeliveryManagement, err = factories.BuildDeliveryManagement(DeliveryManagementDependencies{DeliveryNotifications: deliveryManagementDeliveryNotificationsCapability, DeliveryOutbox: deliveryManagementDeliveryOutboxCapability, DeliveryProjection: deliveryManagementDeliveryProjectionCapability, SqliteTransactionFactory: deliveryManagementSqliteTransactionFactoryCapability})
	if err != nil {
		return Applications{}, fmt.Errorf("yunka assembly: build application delivery/management: %w", err)
	}
	if applications.DeliveryManagement == nil {
		return Applications{}, errors.New("yunka assembly: application factory returned nil for delivery/management")
	}
	return applications, nil
}

type KernelDependencies struct {
	Platform *platform.Provider
	Catalog  *modulecatalog.Catalog
}

func KernelOptions(dependencies KernelDependencies) kernel.Options {
	return kernel.Options{Platform: dependencies.Platform, Catalog: dependencies.Catalog}
}

func ExpectedModuleRequirements() modulecatalog.RequirementSet {
	return modulecatalog.RequirementSet{
		Modules: []string{"delivery"},
	}
}

type TransportBindings struct {
	RPC grpc.ServiceRegistrar
}

func RegisterTransports(bindings TransportBindings, applications Applications, executor operation.Executor) error {
	if executor == nil {
		return errors.New("yunka assembly: operation executor is required for transport registration")
	}
	if bindings.RPC == nil {
		return errors.New("yunka assembly: gRPC registrar is required")
	}
	if applications.DeliveryManagement == nil {
		return errors.New("yunka assembly: application delivery/management is required for transport registration")
	}
	if err := deliveryrpc.RegisterOperationExecutor(bindings.RPC, applications.DeliveryManagement, executor); err != nil {
		return fmt.Errorf("yunka assembly: register gRPC delivery/management: %w", err)
	}
	return nil
}

type RuntimeBindings struct {
	Factories ApplicationFactories
	Executor  operation.Executor
}

// RuntimeBinder constructs consumer-owned execution/application bindings only after kernel.New has prepared the App-owned Platform Provider.
// It does not own lifecycle, discover services, or introduce a second authorization/transaction runtime.
type RuntimeBinder func(context.Context, *platform.Provider) (RuntimeBindings, error)

// RuntimeCapabilityBinder additionally receives the immutable bootstrap-time typed infrastructure capability snapshot.
// Consumers resolve typed values here and pass them into their own ApplicationFactories; business runtime code should not retain the set.
type RuntimeCapabilityBinder func(context.Context, *platform.Provider, modulecatalog.CapabilitySet) (RuntimeBindings, error)

type BootstrapOptions struct {
	Platform                    *platform.Provider
	Factories                   ApplicationFactories
	Executor                    operation.Executor
	AdditionalModules           []modulecatalog.Descriptor
	BindRuntime                 RuntimeBinder
	BindRuntimeWithCapabilities RuntimeCapabilityBinder
	Transports                  TransportBindings
	RuntimeComponents           []core.RuntimeComponent
}

func RuntimeInventory() core.RuntimeInventory {
	return core.RuntimeInventory{
		Routes:              []string{},
		RPCClientConfigured: false,
		RPCServerCount:      1,
	}
}

func Bootstrap(ctx context.Context, options BootstrapOptions) (kernel.BootstrapResult[Applications], error) {
	if options.BindRuntime != nil && options.BindRuntimeWithCapabilities != nil {
		return kernel.BootstrapResult[Applications]{}, fmt.Errorf("yunka assembly: BindRuntime and BindRuntimeWithCapabilities are mutually exclusive")
	}
	if (options.BindRuntime != nil || options.BindRuntimeWithCapabilities != nil) && (options.Factories != nil || options.Executor != nil) {
		return kernel.BootstrapResult[Applications]{}, fmt.Errorf("yunka assembly: runtime binders cannot be combined with prebuilt Factories or Executor")
	}
	catalog, err := NewCatalog(options.AdditionalModules...)
	if err != nil {
		return kernel.BootstrapResult[Applications]{}, fmt.Errorf("yunka assembly: build module catalog: %w", err)
	}
	kernelOptions := KernelOptions(KernelDependencies{Platform: options.Platform, Catalog: catalog})
	kernelOptions.RuntimeComponents = append([]core.RuntimeComponent(nil), options.RuntimeComponents...)
	kernelOptions.RuntimeInventory = RuntimeInventory()
	var runtime RuntimeBindings
	return kernel.Bootstrap(ctx, kernel.BootstrapOptions[Applications]{
		Kernel: kernelOptions,
		BuildWithCapabilities: func(capabilities modulecatalog.CapabilitySet) (Applications, error) {
			if options.BindRuntime == nil && options.BindRuntimeWithCapabilities == nil {
				runtime = RuntimeBindings{Factories: options.Factories, Executor: options.Executor}
				return BuildApplicationsWithCapabilities(options.Factories, options.Executor, capabilities)
			}
			if options.Platform == nil {
				return Applications{}, fmt.Errorf("yunka assembly: Platform is required for runtime binding")
			}
			if options.BindRuntimeWithCapabilities != nil {
				runtime, err = options.BindRuntimeWithCapabilities(ctx, options.Platform, capabilities)
			} else {
				runtime, err = options.BindRuntime(ctx, options.Platform)
			}
			if err != nil {
				return Applications{}, fmt.Errorf("yunka assembly: bind runtime after Platform preparation: %w", err)
			}
			return BuildApplicationsWithCapabilities(runtime.Factories, runtime.Executor, capabilities)
		},
		Register: func(applications Applications) error {
			if options.BindRuntime == nil && options.BindRuntimeWithCapabilities == nil {
				return RegisterTransports(options.Transports, applications, options.Executor)
			}
			return RegisterTransports(options.Transports, applications, runtime.Executor)
		},
	})
}
