// Code generated by yunka assembly compiler; DO NOT EDIT.

package assembly

import (
	"context"
	errors "errors"
	fmt "fmt"
	deliveryapplication "github.com/hvritual/iot-delivery-system/backend-yunka/internal/delivery/application"
	deliveryrpc "github.com/hvritual/iot-delivery-system/backend-yunka/internal/delivery/transport/rpc"
	grpc "google.golang.org/grpc"
	"yunka.io/framework/core"
	modulecatalog "yunka.io/framework/core/modulecatalog"
	kernel "yunka.io/framework/kernel"
	operation "yunka.io/framework/operation"
	platform "yunka.io/framework/platform"
)

const AssemblyPlanDigest = "52fe75305fb70ed9d34fadcb56aaabf79bfc8bcba1f77b5070a31735a9f1882d"

type DeliveryManagementDependencies struct {
}

type ApplicationFactories interface {
	BuildDeliveryManagement(DeliveryManagementDependencies) (deliveryapplication.DeliveryService, error)
}

type Applications struct {
	DeliveryManagement deliveryapplication.DeliveryService
}

func BuildApplications(factories ApplicationFactories, executor operation.Executor) (Applications, error) {
	if factories == nil {
		return Applications{}, errors.New("yunka assembly: application factories are required")
	}
	var applications Applications
	var err error
	applications.DeliveryManagement, err = factories.BuildDeliveryManagement(DeliveryManagementDependencies{})
	if err != nil {
		return Applications{}, fmt.Errorf("yunka assembly: build application delivery/management: %w", err)
	}
	if applications.DeliveryManagement == nil {
		return Applications{}, errors.New("yunka assembly: application factory returned nil for delivery/management")
	}
	return applications, nil
}

type KernelDependencies struct {
	Platform *platform.Provider
	Catalog  *modulecatalog.Catalog
}

func KernelOptions(dependencies KernelDependencies) kernel.Options {
	return kernel.Options{Platform: dependencies.Platform, Catalog: dependencies.Catalog}
}

func ExpectedModuleRequirements() modulecatalog.RequirementSet {
	return modulecatalog.RequirementSet{
		Modules: []string{"delivery"},
	}
}

type TransportBindings struct {
	RPC grpc.ServiceRegistrar
}

func RegisterTransports(bindings TransportBindings, applications Applications, executor operation.Executor) error {
	if executor == nil {
		return errors.New("yunka assembly: operation executor is required for transport registration")
	}
	if bindings.RPC == nil {
		return errors.New("yunka assembly: gRPC registrar is required")
	}
	if applications.DeliveryManagement == nil {
		return errors.New("yunka assembly: application delivery/management is required for transport registration")
	}
	if err := deliveryrpc.RegisterOperationExecutor(bindings.RPC, applications.DeliveryManagement, executor); err != nil {
		return fmt.Errorf("yunka assembly: register gRPC delivery/management: %w", err)
	}
	return nil
}

type RuntimeBindings struct {
	Factories ApplicationFactories
	Executor  operation.Executor
}

// RuntimeBinder constructs consumer-owned execution/application bindings only after kernel.New has prepared the App-owned Platform Provider.
// It does not own lifecycle, discover services, or introduce a second authorization/transaction runtime.
type RuntimeBinder func(context.Context, *platform.Provider) (RuntimeBindings, error)

type BootstrapOptions struct {
	Platform          *platform.Provider
	Factories         ApplicationFactories
	Executor          operation.Executor
	BindRuntime       RuntimeBinder
	Transports        TransportBindings
	RuntimeComponents []core.RuntimeComponent
}

func RuntimeInventory() core.RuntimeInventory {
	return core.RuntimeInventory{
		Routes:              []string{},
		RPCClientConfigured: false,
		RPCServerCount:      1,
	}
}

func Bootstrap(ctx context.Context, options BootstrapOptions) (kernel.BootstrapResult[Applications], error) {
	if options.BindRuntime != nil && (options.Factories != nil || options.Executor != nil) {
		return kernel.BootstrapResult[Applications]{}, fmt.Errorf("yunka assembly: BindRuntime cannot be combined with prebuilt Factories or Executor")
	}
	catalog, err := NewCatalog()
	if err != nil {
		return kernel.BootstrapResult[Applications]{}, fmt.Errorf("yunka assembly: build module catalog: %w", err)
	}
	kernelOptions := KernelOptions(KernelDependencies{Platform: options.Platform, Catalog: catalog})
	kernelOptions.RuntimeComponents = append([]core.RuntimeComponent(nil), options.RuntimeComponents...)
	kernelOptions.RuntimeInventory = RuntimeInventory()
	var runtime RuntimeBindings
	return kernel.Bootstrap(ctx, kernel.BootstrapOptions[Applications]{
		Kernel: kernelOptions,
		Build: func() (Applications, error) {
			if options.BindRuntime == nil {
				runtime = RuntimeBindings{Factories: options.Factories, Executor: options.Executor}
				return BuildApplications(options.Factories, options.Executor)
			}
			if options.Platform == nil {
				return Applications{}, fmt.Errorf("yunka assembly: Platform is required for BindRuntime")
			}
			runtime, err = options.BindRuntime(ctx, options.Platform)
			if err != nil {
				return Applications{}, fmt.Errorf("yunka assembly: bind runtime after Platform preparation: %w", err)
			}
			return BuildApplications(runtime.Factories, runtime.Executor)
		},
		Register: func(applications Applications) error {
			if options.BindRuntime == nil {
				return RegisterTransports(options.Transports, applications, options.Executor)
			}
			return RegisterTransports(options.Transports, applications, runtime.Executor)
		},
	})
}
