// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: delivery/v1/dashboard.proto

package deliveryv1

import (
	_ "github.com/hvritual/yunka.io/pkg/contractdsl/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardRequest) Reset() {
	*x = GetDashboardRequest{}
	mi := &file_delivery_v1_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardRequest) ProtoMessage() {}

func (x *GetDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_dashboard_proto_rawDescGZIP(), []int{0}
}

type GetDashboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dashboard     *Dashboard             `protobuf:"bytes,1,opt,name=dashboard,proto3" json:"dashboard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardResponse) Reset() {
	*x = GetDashboardResponse{}
	mi := &file_delivery_v1_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardResponse) ProtoMessage() {}

func (x *GetDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardResponse.ProtoReflect.Descriptor instead.
func (*GetDashboardResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *GetDashboardResponse) GetDashboard() *Dashboard {
	if x != nil {
		return x.Dashboard
	}
	return nil
}

type Dashboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boards        []*BoardSummary        `protobuf:"bytes,1,rep,name=boards,proto3" json:"boards,omitempty"`
	Items         []*WorkItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dashboard) Reset() {
	*x = Dashboard{}
	mi := &file_delivery_v1_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dashboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dashboard) ProtoMessage() {}

func (x *Dashboard) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dashboard.ProtoReflect.Descriptor instead.
func (*Dashboard) Descriptor() ([]byte, []int) {
	return file_delivery_v1_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *Dashboard) GetBoards() []*BoardSummary {
	if x != nil {
		return x.Boards
	}
	return nil
}

func (x *Dashboard) GetItems() []*WorkItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Dashboard) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

type BoardSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         string                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Active        int32                  `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Blocked       int32                  `protobuf:"varint,4,opt,name=blocked,proto3" json:"blocked,omitempty"`
	Verifying     int32                  `protobuf:"varint,5,opt,name=verifying,proto3" json:"verifying,omitempty"`
	Released      int32                  `protobuf:"varint,6,opt,name=released,proto3" json:"released,omitempty"`
	Closed        int32                  `protobuf:"varint,7,opt,name=closed,proto3" json:"closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardSummary) Reset() {
	*x = BoardSummary{}
	mi := &file_delivery_v1_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardSummary) ProtoMessage() {}

func (x *BoardSummary) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardSummary.ProtoReflect.Descriptor instead.
func (*BoardSummary) Descriptor() ([]byte, []int) {
	return file_delivery_v1_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *BoardSummary) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *BoardSummary) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BoardSummary) GetActive() int32 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *BoardSummary) GetBlocked() int32 {
	if x != nil {
		return x.Blocked
	}
	return 0
}

func (x *BoardSummary) GetVerifying() int32 {
	if x != nil {
		return x.Verifying
	}
	return 0
}

func (x *BoardSummary) GetReleased() int32 {
	if x != nil {
		return x.Released
	}
	return 0
}

func (x *BoardSummary) GetClosed() int32 {
	if x != nil {
		return x.Closed
	}
	return 0
}

var File_delivery_v1_dashboard_proto protoreflect.FileDescriptor

const file_delivery_v1_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x1bdelivery/v1/dashboard.proto\x12\x0fiot.delivery.v1\x1a\x1ayunka/dsl/v1/options.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bdelivery/v1/work_item.proto\"\x1d\n" +
	"\x13GetDashboardRequest:\x06\xd2\xf3\x18\x02\b\x01\"X\n" +
	"\x14GetDashboardResponse\x128\n" +
	"\tdashboard\x18\x01 \x01(\v2\x1a.iot.delivery.v1.DashboardR\tdashboard:\x06\xd2\xf3\x18\x02\b\x02\"\xba\x01\n" +
	"\tDashboard\x125\n" +
	"\x06boards\x18\x01 \x03(\v2\x1d.iot.delivery.v1.BoardSummaryR\x06boards\x12/\n" +
	"\x05items\x18\x02 \x03(\v2\x19.iot.delivery.v1.WorkItemR\x05items\x12=\n" +
	"\fgenerated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt:\x06\xd2\xf3\x18\x02\b\x03\"\xc6\x01\n" +
	"\fBoardSummary\x12\x14\n" +
	"\x05board\x18\x01 \x01(\tR\x05board\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x16\n" +
	"\x06active\x18\x03 \x01(\x05R\x06active\x12\x18\n" +
	"\ablocked\x18\x04 \x01(\x05R\ablocked\x12\x1c\n" +
	"\tverifying\x18\x05 \x01(\x05R\tverifying\x12\x1a\n" +
	"\breleased\x18\x06 \x01(\x05R\breleased\x12\x16\n" +
	"\x06closed\x18\a \x01(\x05R\x06closed:\x06\xd2\xf3\x18\x02\b\x03BXZVgithub.com/hvritual/iot-delivery-system/backend-yunka/contracts/delivery/v1;deliveryv1b\x06proto3"

var (
	file_delivery_v1_dashboard_proto_rawDescOnce sync.Once
	file_delivery_v1_dashboard_proto_rawDescData []byte
)

func file_delivery_v1_dashboard_proto_rawDescGZIP() []byte {
	file_delivery_v1_dashboard_proto_rawDescOnce.Do(func() {
		file_delivery_v1_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delivery_v1_dashboard_proto_rawDesc), len(file_delivery_v1_dashboard_proto_rawDesc)))
	})
	return file_delivery_v1_dashboard_proto_rawDescData
}

var file_delivery_v1_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_delivery_v1_dashboard_proto_goTypes = []any{
	(*GetDashboardRequest)(nil),   // 0: iot.delivery.v1.GetDashboardRequest
	(*GetDashboardResponse)(nil),  // 1: iot.delivery.v1.GetDashboardResponse
	(*Dashboard)(nil),             // 2: iot.delivery.v1.Dashboard
	(*BoardSummary)(nil),          // 3: iot.delivery.v1.BoardSummary
	(*WorkItem)(nil),              // 4: iot.delivery.v1.WorkItem
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_delivery_v1_dashboard_proto_depIdxs = []int32{
	2, // 0: iot.delivery.v1.GetDashboardResponse.dashboard:type_name -> iot.delivery.v1.Dashboard
	3, // 1: iot.delivery.v1.Dashboard.boards:type_name -> iot.delivery.v1.BoardSummary
	4, // 2: iot.delivery.v1.Dashboard.items:type_name -> iot.delivery.v1.WorkItem
	5, // 3: iot.delivery.v1.Dashboard.generated_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_delivery_v1_dashboard_proto_init() }
func file_delivery_v1_dashboard_proto_init() {
	if File_delivery_v1_dashboard_proto != nil {
		return
	}
	file_delivery_v1_work_item_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delivery_v1_dashboard_proto_rawDesc), len(file_delivery_v1_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_delivery_v1_dashboard_proto_goTypes,
		DependencyIndexes: file_delivery_v1_dashboard_proto_depIdxs,
		MessageInfos:      file_delivery_v1_dashboard_proto_msgTypes,
	}.Build()
	File_delivery_v1_dashboard_proto = out.File
	file_delivery_v1_dashboard_proto_goTypes = nil
	file_delivery_v1_dashboard_proto_depIdxs = nil
}
