// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: delivery/v1/delivery_service.proto

package deliveryv1

import (
	_ "github.com/hvritual/yunka.io/pkg/contractdsl/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_delivery_v1_delivery_service_proto protoreflect.FileDescriptor

const file_delivery_v1_delivery_service_proto_rawDesc = "" +
	"\n" +
	"\"delivery/v1/delivery_service.proto\x12\x0fiot.delivery.v1\x1a\x1ayunka/dsl/v1/options.proto\x1a\x18delivery/v1/common.proto\x1a\x1bdelivery/v1/work_item.proto\x1a\x19delivery/v1/project.proto\x1a\x1adelivery/v1/planning.proto\x1a\x1bdelivery/v1/dashboard.proto\x1a\x1cdelivery/v1/saved_view.proto\x1a\x1edelivery/v1/notification.proto2\xe1'\n" +
	"\x0fDeliveryService\x12\xae\x01\n" +
	"\fGetDashboard\x12$.iot.delivery.v1.GetDashboardRequest\x1a%.iot.delivery.v1.GetDashboardResponse\"Q\xe2\xf3\x18M\n" +
	"\x16delivery.dashboard.get\x12\rget_dashboard\x1a\x17delivery.dashboard.read2\x03\x02\x01\x03H\x01R\x04\b\x02\x10\x01\x12\xa0\x01\n" +
	"\tListItems\x12!.iot.delivery.v1.ListItemsRequest\x1a\".iot.delivery.v1.ListItemsResponse\"L\xe2\xf3\x18H\n" +
	"\x13delivery.items.list\x12\n" +
	"list_items\x1a\x18delivery.work-items.read2\x03\x02\x01\x03H\x01R\x04\b\x02\x10\x01\x12\xa6\x01\n" +
	"\n" +
	"CreateItem\x12\".iot.delivery.v1.CreateItemRequest\x1a!.iot.delivery.v1.WorkItemResponse\"Q\xe2\xf3\x18M\n" +
	"\x15delivery.items.create\x12\vcreate_item\x1a\x1adelivery.work-items.create2\x03\x02\x01\x03H\x01R\x04\b\x03\x10\x01\x12\xeb\x01\n" +
	"\n" +
	"UpdateItem\x12\".iot.delivery.v1.UpdateItemRequest\x1a!.iot.delivery.v1.WorkItemResponse\"\x95\x01\xe2\xf3\x18\x90\x01\n" +
	"\x15delivery.items.update\x12\vupdate_item\x1a\x1adelivery.work-items.update\x1a\"delivery.work-items.context.update2\x03\x02\x01\x03B\x1ddelivery.items.update-contextH\x01R\x04\b\x03\x10\x01\x12\xc3\x01\n" +
	"\x11CreateItemComment\x12).iot.delivery.v1.CreateItemCommentRequest\x1a .iot.delivery.v1.CommentResponse\"a\xe2\xf3\x18]\n" +
	"\x1ddelivery.items.comment.create\x12\vadd_comment\x1a\"delivery.work-items.comment.create2\x03\x02\x01\x03H\x01R\x04\b\x03\x10\x01\x12\xcc\x01\n" +
	"\x11UpdateItemContext\x12).iot.delivery.v1.UpdateItemContextRequest\x1a!.iot.delivery.v1.WorkItemResponse\"i\xe2\xf3\x18e\n" +
	"\x1ddelivery.items.update-context\x12\x13update_item_context\x1a\"delivery.work-items.context.update2\x03\x02\x01\x03H\x01R\x04\b\x03\x10\x01\x12\xb5\x01\n" +
	"\vAdvanceGate\x12#.iot.delivery.v1.AdvanceGateRequest\x1a!.iot.delivery.v1.WorkItemResponse\"^\xe2\xf3\x18Z\n" +
	"\x1bdelivery.items.advance-gate\x12\fadvance_gate\x1a delivery.work-items.gate.advance2\x03\x02\x01\x03H\x01R\x04\b\x03\x10\x01\x12\xa1\x01\n" +
	"\tCloseItem\x12!.iot.delivery.v1.CloseItemRequest\x1a!.iot.delivery.v1.WorkItemResponse\"N\xe2\xf3\x18J\n" +
	"\x14delivery.items.close\x12\n" +
	"close_item\x1a\x19delivery.work-items.close2\x03\x02\x01\x03H\x01R\x04\b\x03\x10\x01\x12\x9a\x01\n" +
	"\bSaveView\x12 .iot.delivery.v1.SaveViewRequest\x1a\".iot.delivery.v1.SavedViewResponse\"H\xe2\xf3\x18D\n" +
	"\x13delivery.views.save\x12\tsave_view\x1a\x14delivery.views.write(\x012\x02\x02\x01H\x01R\x04\b\x03\x10\x01\x12\xb1\x01\n" +
	"\x0eListSavedViews\x12&.iot.delivery.v1.ListSavedViewsRequest\x1a'.iot.delivery.v1.ListSavedViewsResponse\"N\xe2\xf3\x18J\n" +
	"\x13delivery.views.list\x12\x10list_saved_views\x1a\x13delivery.views.read(\x012\x02\x02\x01H\x01R\x04\b\x02\x10\x01\x12\xaf\x01\n" +
	"\rGetMemberWeek\x12%.iot.delivery.v1.GetMemberWeekRequest\x1a#.iot.delivery.v1.MemberWeekResponse\"R\xe2\xf3\x18N\n" +
	"\x15delivery.members.week\x12\x0fget_member_week\x1a\x15delivery.members.read(\x012\x03\x02\x01\x03H\x01R\x04\b\x02\x10\x01\x12\xb1\x01\n" +
	"\rCreateProject\x12%.iot.delivery.v1.CreateProjectRequest\x1a .iot.delivery.v1.ProjectResponse\"W\xe2\xf3\x18S\n" +
	"\x18delivery.projects.create\x12\x0ecreate_project\x1a\x18delivery.projects.create(\x012\x03\x02\x01\x03H\x01R\x04\b\x03\x10\x01\x12\xaf\x01\n" +
	"\rCreateRelease\x12%.iot.delivery.v1.CreateReleaseRequest\x1a .iot.delivery.v1.ReleaseResponse\"U\xe2\xf3\x18Q\n" +
	"\x18delivery.releases.create\x12\x0ecreate_release\x1a\x18delivery.releases.create2\x03\x02\x01\x03H\x01R\x04\b\x03\x10\x01\x12\xa9\x01\n" +
	"\fCreateSprint\x12$.iot.delivery.v1.CreateSprintRequest\x1a\x1f.iot.delivery.v1.SprintResponse\"R\xe2\xf3\x18N\n" +
	"\x17delivery.sprints.create\x12\rcreate_sprint\x1a\x17delivery.sprints.create2\x03\x02\x01\x03H\x01R\x04\b\x03\x10\x01\x12\xbb\x01\n" +
	"\x0fCreateMilestone\x12'.iot.delivery.v1.CreateMilestoneRequest\x1a\".iot.delivery.v1.MilestoneResponse\"[\xe2\xf3\x18W\n" +
	"\x1adelivery.milestones.create\x12\x10create_milestone\x1a\x1adelivery.milestones.create2\x03\x02\x01\x03H\x01R\x04\b\x03\x10\x01\x12\xaf\x01\n" +
	"\fListProjects\x12$.iot.delivery.v1.ListProjectsRequest\x1a%.iot.delivery.v1.ListProjectsResponse\"R\xe2\xf3\x18N\n" +
	"\x16delivery.projects.list\x12\rlist_projects\x1a\x16delivery.projects.read(\x012\x03\x02\x01\x03H\x01R\x04\b\x02\x10\x01\x12\xaf\x01\n" +
	"\fListReleases\x12$.iot.delivery.v1.ListReleasesRequest\x1a%.iot.delivery.v1.ListReleasesResponse\"R\xe2\xf3\x18N\n" +
	"\x16delivery.releases.list\x12\rlist_releases\x1a\x16delivery.releases.read(\x012\x03\x02\x01\x03H\x01R\x04\b\x02\x10\x01\x12\xa9\x01\n" +
	"\vListSprints\x12#.iot.delivery.v1.ListSprintsRequest\x1a$.iot.delivery.v1.ListSprintsResponse\"O\xe2\xf3\x18K\n" +
	"\x15delivery.sprints.list\x12\flist_sprints\x1a\x15delivery.sprints.read(\x012\x03\x02\x01\x03H\x01R\x04\b\x02\x10\x01\x12\xbb\x01\n" +
	"\x0eListMilestones\x12&.iot.delivery.v1.ListMilestonesRequest\x1a'.iot.delivery.v1.ListMilestonesResponse\"X\xe2\xf3\x18T\n" +
	"\x18delivery.milestones.list\x12\x0flist_milestones\x1a\x18delivery.milestones.read(\x012\x03\x02\x01\x03H\x01R\x04\b\x02\x10\x01\x12\x9a\x01\n" +
	"\aGetItem\x12\x1f.iot.delivery.v1.GetItemRequest\x1a!.iot.delivery.v1.WorkItemResponse\"K\xe2\xf3\x18G\n" +
	"\x12delivery.items.get\x12\bget_item\x1a\x18delivery.work-items.read(\x012\x03\x02\x01\x03H\x01R\x04\b\x02\x10\x01\x12\xac\x01\n" +
	"\vSearchItems\x12#.iot.delivery.v1.SearchItemsRequest\x1a$.iot.delivery.v1.SearchItemsResponse\"R\xe2\xf3\x18N\n" +
	"\x15delivery.items.search\x12\fsearch_items\x1a\x18delivery.work-items.read(\x012\x03\x02\x01\x03H\x01R\x04\b\x02\x10\x01\x12\xc5\x01\n" +
	"\x10FindSimilarItems\x12(.iot.delivery.v1.FindSimilarItemsRequest\x1a).iot.delivery.v1.FindSimilarItemsResponse\"\\\xe2\xf3\x18X\n" +
	"\x19delivery.items.similarity\x12\x12find_similar_items\x1a\x18delivery.work-items.read(\x012\x03\x02\x01\x03H\x01R\x04\b\x02\x10\x01\x12\xc9\x01\n" +
	"\x12GetProjectProgress\x12*.iot.delivery.v1.GetProjectProgressRequest\x1a(.iot.delivery.v1.ProjectProgressResponse\"]\xe2\xf3\x18Y\n" +
	"\x1adelivery.projects.progress\x12\x14get_project_progress\x1a\x16delivery.projects.read(\x012\x03\x02\x01\x03H\x01R\x04\b\x02\x10\x01\x12\xc9\x01\n" +
	"\x12GetProjectSchedule\x12*.iot.delivery.v1.GetProjectScheduleRequest\x1a(.iot.delivery.v1.ProjectScheduleResponse\"]\xe2\xf3\x18Y\n" +
	"\x1adelivery.projects.schedule\x12\x14get_project_schedule\x1a\x16delivery.projects.read(\x012\x03\x02\x01\x03H\x01R\x04\b\x02\x10\x01\x12\xca\x01\n" +
	"\x11ListNotifications\x12).iot.delivery.v1.ListNotificationsRequest\x1a*.iot.delivery.v1.ListNotificationsResponse\"^\xe2\xf3\x18Z\n" +
	"\x1bdelivery.notifications.list\x12\x12list_notifications\x1a\x18delivery.work-items.read(\x012\x03\x02\x01\x03H\x01R\x04\b\x02\x10\x01\x1a\xd7\x03\xda\xf3\x18\xd2\x03\n" +
	"\n" +
	"management\"m\n" +
	"\x1asqlite.transaction-factory\x12Fgithub.com/hvritual/iot-delivery-system/backend-yunka/internal/localtx\x1a\aFactory\"i\n" +
	"\x0fdelivery.outbox\x12Ngithub.com/hvritual/iot-delivery-system/backend-yunka/internal/deliveryruntime\x1a\x06Outbox\"w\n" +
	"\x16delivery.notifications\x12Ngithub.com/hvritual/iot-delivery-system/backend-yunka/internal/deliveryruntime\x1a\rNotifications\"q\n" +
	"\x13delivery.projection\x12Ngithub.com/hvritual/iot-delivery-system/backend-yunka/internal/deliveryruntime\x1a\n" +
	"ProjectionBj\xca\xf3\x18\x0e\n" +
	"\bdelivery\x12\x02v1ZVgithub.com/hvritual/iot-delivery-system/backend-yunka/contracts/delivery/v1;deliveryv1b\x06proto3"

var file_delivery_v1_delivery_service_proto_goTypes = []any{
	(*GetDashboardRequest)(nil),       // 0: iot.delivery.v1.GetDashboardRequest
	(*ListItemsRequest)(nil),          // 1: iot.delivery.v1.ListItemsRequest
	(*CreateItemRequest)(nil),         // 2: iot.delivery.v1.CreateItemRequest
	(*UpdateItemRequest)(nil),         // 3: iot.delivery.v1.UpdateItemRequest
	(*CreateItemCommentRequest)(nil),  // 4: iot.delivery.v1.CreateItemCommentRequest
	(*UpdateItemContextRequest)(nil),  // 5: iot.delivery.v1.UpdateItemContextRequest
	(*AdvanceGateRequest)(nil),        // 6: iot.delivery.v1.AdvanceGateRequest
	(*CloseItemRequest)(nil),          // 7: iot.delivery.v1.CloseItemRequest
	(*SaveViewRequest)(nil),           // 8: iot.delivery.v1.SaveViewRequest
	(*ListSavedViewsRequest)(nil),     // 9: iot.delivery.v1.ListSavedViewsRequest
	(*GetMemberWeekRequest)(nil),      // 10: iot.delivery.v1.GetMemberWeekRequest
	(*CreateProjectRequest)(nil),      // 11: iot.delivery.v1.CreateProjectRequest
	(*CreateReleaseRequest)(nil),      // 12: iot.delivery.v1.CreateReleaseRequest
	(*CreateSprintRequest)(nil),       // 13: iot.delivery.v1.CreateSprintRequest
	(*CreateMilestoneRequest)(nil),    // 14: iot.delivery.v1.CreateMilestoneRequest
	(*ListProjectsRequest)(nil),       // 15: iot.delivery.v1.ListProjectsRequest
	(*ListReleasesRequest)(nil),       // 16: iot.delivery.v1.ListReleasesRequest
	(*ListSprintsRequest)(nil),        // 17: iot.delivery.v1.ListSprintsRequest
	(*ListMilestonesRequest)(nil),     // 18: iot.delivery.v1.ListMilestonesRequest
	(*GetItemRequest)(nil),            // 19: iot.delivery.v1.GetItemRequest
	(*SearchItemsRequest)(nil),        // 20: iot.delivery.v1.SearchItemsRequest
	(*FindSimilarItemsRequest)(nil),   // 21: iot.delivery.v1.FindSimilarItemsRequest
	(*GetProjectProgressRequest)(nil), // 22: iot.delivery.v1.GetProjectProgressRequest
	(*GetProjectScheduleRequest)(nil), // 23: iot.delivery.v1.GetProjectScheduleRequest
	(*ListNotificationsRequest)(nil),  // 24: iot.delivery.v1.ListNotificationsRequest
	(*GetDashboardResponse)(nil),      // 25: iot.delivery.v1.GetDashboardResponse
	(*ListItemsResponse)(nil),         // 26: iot.delivery.v1.ListItemsResponse
	(*WorkItemResponse)(nil),          // 27: iot.delivery.v1.WorkItemResponse
	(*CommentResponse)(nil),           // 28: iot.delivery.v1.CommentResponse
	(*SavedViewResponse)(nil),         // 29: iot.delivery.v1.SavedViewResponse
	(*ListSavedViewsResponse)(nil),    // 30: iot.delivery.v1.ListSavedViewsResponse
	(*MemberWeekResponse)(nil),        // 31: iot.delivery.v1.MemberWeekResponse
	(*ProjectResponse)(nil),           // 32: iot.delivery.v1.ProjectResponse
	(*ReleaseResponse)(nil),           // 33: iot.delivery.v1.ReleaseResponse
	(*SprintResponse)(nil),            // 34: iot.delivery.v1.SprintResponse
	(*MilestoneResponse)(nil),         // 35: iot.delivery.v1.MilestoneResponse
	(*ListProjectsResponse)(nil),      // 36: iot.delivery.v1.ListProjectsResponse
	(*ListReleasesResponse)(nil),      // 37: iot.delivery.v1.ListReleasesResponse
	(*ListSprintsResponse)(nil),       // 38: iot.delivery.v1.ListSprintsResponse
	(*ListMilestonesResponse)(nil),    // 39: iot.delivery.v1.ListMilestonesResponse
	(*SearchItemsResponse)(nil),       // 40: iot.delivery.v1.SearchItemsResponse
	(*FindSimilarItemsResponse)(nil),  // 41: iot.delivery.v1.FindSimilarItemsResponse
	(*ProjectProgressResponse)(nil),   // 42: iot.delivery.v1.ProjectProgressResponse
	(*ProjectScheduleResponse)(nil),   // 43: iot.delivery.v1.ProjectScheduleResponse
	(*ListNotificationsResponse)(nil), // 44: iot.delivery.v1.ListNotificationsResponse
}
var file_delivery_v1_delivery_service_proto_depIdxs = []int32{
	0,  // 0: iot.delivery.v1.DeliveryService.GetDashboard:input_type -> iot.delivery.v1.GetDashboardRequest
	1,  // 1: iot.delivery.v1.DeliveryService.ListItems:input_type -> iot.delivery.v1.ListItemsRequest
	2,  // 2: iot.delivery.v1.DeliveryService.CreateItem:input_type -> iot.delivery.v1.CreateItemRequest
	3,  // 3: iot.delivery.v1.DeliveryService.UpdateItem:input_type -> iot.delivery.v1.UpdateItemRequest
	4,  // 4: iot.delivery.v1.DeliveryService.CreateItemComment:input_type -> iot.delivery.v1.CreateItemCommentRequest
	5,  // 5: iot.delivery.v1.DeliveryService.UpdateItemContext:input_type -> iot.delivery.v1.UpdateItemContextRequest
	6,  // 6: iot.delivery.v1.DeliveryService.AdvanceGate:input_type -> iot.delivery.v1.AdvanceGateRequest
	7,  // 7: iot.delivery.v1.DeliveryService.CloseItem:input_type -> iot.delivery.v1.CloseItemRequest
	8,  // 8: iot.delivery.v1.DeliveryService.SaveView:input_type -> iot.delivery.v1.SaveViewRequest
	9,  // 9: iot.delivery.v1.DeliveryService.ListSavedViews:input_type -> iot.delivery.v1.ListSavedViewsRequest
	10, // 10: iot.delivery.v1.DeliveryService.GetMemberWeek:input_type -> iot.delivery.v1.GetMemberWeekRequest
	11, // 11: iot.delivery.v1.DeliveryService.CreateProject:input_type -> iot.delivery.v1.CreateProjectRequest
	12, // 12: iot.delivery.v1.DeliveryService.CreateRelease:input_type -> iot.delivery.v1.CreateReleaseRequest
	13, // 13: iot.delivery.v1.DeliveryService.CreateSprint:input_type -> iot.delivery.v1.CreateSprintRequest
	14, // 14: iot.delivery.v1.DeliveryService.CreateMilestone:input_type -> iot.delivery.v1.CreateMilestoneRequest
	15, // 15: iot.delivery.v1.DeliveryService.ListProjects:input_type -> iot.delivery.v1.ListProjectsRequest
	16, // 16: iot.delivery.v1.DeliveryService.ListReleases:input_type -> iot.delivery.v1.ListReleasesRequest
	17, // 17: iot.delivery.v1.DeliveryService.ListSprints:input_type -> iot.delivery.v1.ListSprintsRequest
	18, // 18: iot.delivery.v1.DeliveryService.ListMilestones:input_type -> iot.delivery.v1.ListMilestonesRequest
	19, // 19: iot.delivery.v1.DeliveryService.GetItem:input_type -> iot.delivery.v1.GetItemRequest
	20, // 20: iot.delivery.v1.DeliveryService.SearchItems:input_type -> iot.delivery.v1.SearchItemsRequest
	21, // 21: iot.delivery.v1.DeliveryService.FindSimilarItems:input_type -> iot.delivery.v1.FindSimilarItemsRequest
	22, // 22: iot.delivery.v1.DeliveryService.GetProjectProgress:input_type -> iot.delivery.v1.GetProjectProgressRequest
	23, // 23: iot.delivery.v1.DeliveryService.GetProjectSchedule:input_type -> iot.delivery.v1.GetProjectScheduleRequest
	24, // 24: iot.delivery.v1.DeliveryService.ListNotifications:input_type -> iot.delivery.v1.ListNotificationsRequest
	25, // 25: iot.delivery.v1.DeliveryService.GetDashboard:output_type -> iot.delivery.v1.GetDashboardResponse
	26, // 26: iot.delivery.v1.DeliveryService.ListItems:output_type -> iot.delivery.v1.ListItemsResponse
	27, // 27: iot.delivery.v1.DeliveryService.CreateItem:output_type -> iot.delivery.v1.WorkItemResponse
	27, // 28: iot.delivery.v1.DeliveryService.UpdateItem:output_type -> iot.delivery.v1.WorkItemResponse
	28, // 29: iot.delivery.v1.DeliveryService.CreateItemComment:output_type -> iot.delivery.v1.CommentResponse
	27, // 30: iot.delivery.v1.DeliveryService.UpdateItemContext:output_type -> iot.delivery.v1.WorkItemResponse
	27, // 31: iot.delivery.v1.DeliveryService.AdvanceGate:output_type -> iot.delivery.v1.WorkItemResponse
	27, // 32: iot.delivery.v1.DeliveryService.CloseItem:output_type -> iot.delivery.v1.WorkItemResponse
	29, // 33: iot.delivery.v1.DeliveryService.SaveView:output_type -> iot.delivery.v1.SavedViewResponse
	30, // 34: iot.delivery.v1.DeliveryService.ListSavedViews:output_type -> iot.delivery.v1.ListSavedViewsResponse
	31, // 35: iot.delivery.v1.DeliveryService.GetMemberWeek:output_type -> iot.delivery.v1.MemberWeekResponse
	32, // 36: iot.delivery.v1.DeliveryService.CreateProject:output_type -> iot.delivery.v1.ProjectResponse
	33, // 37: iot.delivery.v1.DeliveryService.CreateRelease:output_type -> iot.delivery.v1.ReleaseResponse
	34, // 38: iot.delivery.v1.DeliveryService.CreateSprint:output_type -> iot.delivery.v1.SprintResponse
	35, // 39: iot.delivery.v1.DeliveryService.CreateMilestone:output_type -> iot.delivery.v1.MilestoneResponse
	36, // 40: iot.delivery.v1.DeliveryService.ListProjects:output_type -> iot.delivery.v1.ListProjectsResponse
	37, // 41: iot.delivery.v1.DeliveryService.ListReleases:output_type -> iot.delivery.v1.ListReleasesResponse
	38, // 42: iot.delivery.v1.DeliveryService.ListSprints:output_type -> iot.delivery.v1.ListSprintsResponse
	39, // 43: iot.delivery.v1.DeliveryService.ListMilestones:output_type -> iot.delivery.v1.ListMilestonesResponse
	27, // 44: iot.delivery.v1.DeliveryService.GetItem:output_type -> iot.delivery.v1.WorkItemResponse
	40, // 45: iot.delivery.v1.DeliveryService.SearchItems:output_type -> iot.delivery.v1.SearchItemsResponse
	41, // 46: iot.delivery.v1.DeliveryService.FindSimilarItems:output_type -> iot.delivery.v1.FindSimilarItemsResponse
	42, // 47: iot.delivery.v1.DeliveryService.GetProjectProgress:output_type -> iot.delivery.v1.ProjectProgressResponse
	43, // 48: iot.delivery.v1.DeliveryService.GetProjectSchedule:output_type -> iot.delivery.v1.ProjectScheduleResponse
	44, // 49: iot.delivery.v1.DeliveryService.ListNotifications:output_type -> iot.delivery.v1.ListNotificationsResponse
	25, // [25:50] is the sub-list for method output_type
	0,  // [0:25] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_delivery_v1_delivery_service_proto_init() }
func file_delivery_v1_delivery_service_proto_init() {
	if File_delivery_v1_delivery_service_proto != nil {
		return
	}
	file_delivery_v1_common_proto_init()
	file_delivery_v1_work_item_proto_init()
	file_delivery_v1_project_proto_init()
	file_delivery_v1_planning_proto_init()
	file_delivery_v1_dashboard_proto_init()
	file_delivery_v1_saved_view_proto_init()
	file_delivery_v1_notification_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delivery_v1_delivery_service_proto_rawDesc), len(file_delivery_v1_delivery_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_delivery_v1_delivery_service_proto_goTypes,
		DependencyIndexes: file_delivery_v1_delivery_service_proto_depIdxs,
	}.Build()
	File_delivery_v1_delivery_service_proto = out.File
	file_delivery_v1_delivery_service_proto_goTypes = nil
	file_delivery_v1_delivery_service_proto_depIdxs = nil
}
