// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: iot_delivery.proto

package deliveryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeliveryService_GetDashboard_FullMethodName      = "/iot.delivery.v1.DeliveryService/GetDashboard"
	DeliveryService_ListItems_FullMethodName         = "/iot.delivery.v1.DeliveryService/ListItems"
	DeliveryService_CreateItem_FullMethodName        = "/iot.delivery.v1.DeliveryService/CreateItem"
	DeliveryService_UpdateItemContext_FullMethodName = "/iot.delivery.v1.DeliveryService/UpdateItemContext"
	DeliveryService_AdvanceGate_FullMethodName       = "/iot.delivery.v1.DeliveryService/AdvanceGate"
	DeliveryService_CloseItem_FullMethodName         = "/iot.delivery.v1.DeliveryService/CloseItem"
)

// DeliveryServiceClient is the client API for DeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DeliveryService is the transport-neutral contract for the existing desktop
// MVP. HTTP remains the compatibility adapter; generated gRPC types establish
// an explicit evolution boundary for future integrations.
type DeliveryServiceClient interface {
	GetDashboard(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardResponse, error)
	ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error)
	CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*WorkItemResponse, error)
	UpdateItemContext(ctx context.Context, in *UpdateItemContextRequest, opts ...grpc.CallOption) (*WorkItemResponse, error)
	AdvanceGate(ctx context.Context, in *AdvanceGateRequest, opts ...grpc.CallOption) (*WorkItemResponse, error)
	CloseItem(ctx context.Context, in *CloseItemRequest, opts ...grpc.CallOption) (*WorkItemResponse, error)
}

type deliveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeliveryServiceClient(cc grpc.ClientConnInterface) DeliveryServiceClient {
	return &deliveryServiceClient{cc}
}

func (c *deliveryServiceClient) GetDashboard(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardResponse)
	err := c.cc.Invoke(ctx, DeliveryService_GetDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemsResponse)
	err := c.cc.Invoke(ctx, DeliveryService_ListItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*WorkItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkItemResponse)
	err := c.cc.Invoke(ctx, DeliveryService_CreateItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) UpdateItemContext(ctx context.Context, in *UpdateItemContextRequest, opts ...grpc.CallOption) (*WorkItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkItemResponse)
	err := c.cc.Invoke(ctx, DeliveryService_UpdateItemContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) AdvanceGate(ctx context.Context, in *AdvanceGateRequest, opts ...grpc.CallOption) (*WorkItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkItemResponse)
	err := c.cc.Invoke(ctx, DeliveryService_AdvanceGate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) CloseItem(ctx context.Context, in *CloseItemRequest, opts ...grpc.CallOption) (*WorkItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkItemResponse)
	err := c.cc.Invoke(ctx, DeliveryService_CloseItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeliveryServiceServer is the server API for DeliveryService service.
// All implementations should embed UnimplementedDeliveryServiceServer
// for forward compatibility.
//
// DeliveryService is the transport-neutral contract for the existing desktop
// MVP. HTTP remains the compatibility adapter; generated gRPC types establish
// an explicit evolution boundary for future integrations.
type DeliveryServiceServer interface {
	GetDashboard(context.Context, *GetDashboardRequest) (*GetDashboardResponse, error)
	ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error)
	CreateItem(context.Context, *CreateItemRequest) (*WorkItemResponse, error)
	UpdateItemContext(context.Context, *UpdateItemContextRequest) (*WorkItemResponse, error)
	AdvanceGate(context.Context, *AdvanceGateRequest) (*WorkItemResponse, error)
	CloseItem(context.Context, *CloseItemRequest) (*WorkItemResponse, error)
}

// UnimplementedDeliveryServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeliveryServiceServer struct{}

func (UnimplementedDeliveryServiceServer) GetDashboard(context.Context, *GetDashboardRequest) (*GetDashboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDashboard not implemented")
}
func (UnimplementedDeliveryServiceServer) ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListItems not implemented")
}
func (UnimplementedDeliveryServiceServer) CreateItem(context.Context, *CreateItemRequest) (*WorkItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateItem not implemented")
}
func (UnimplementedDeliveryServiceServer) UpdateItemContext(context.Context, *UpdateItemContextRequest) (*WorkItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateItemContext not implemented")
}
func (UnimplementedDeliveryServiceServer) AdvanceGate(context.Context, *AdvanceGateRequest) (*WorkItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdvanceGate not implemented")
}
func (UnimplementedDeliveryServiceServer) CloseItem(context.Context, *CloseItemRequest) (*WorkItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseItem not implemented")
}
func (UnimplementedDeliveryServiceServer) testEmbeddedByValue() {}

// UnsafeDeliveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeliveryServiceServer will
// result in compilation errors.
type UnsafeDeliveryServiceServer interface {
	mustEmbedUnimplementedDeliveryServiceServer()
}

func RegisterDeliveryServiceServer(s grpc.ServiceRegistrar, srv DeliveryServiceServer) {
	// If the following call panics, it indicates UnimplementedDeliveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeliveryService_ServiceDesc, srv)
}

func _DeliveryService_GetDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).GetDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_GetDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).GetDashboard(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_ListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).ListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_ListItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).ListItems(ctx, req.(*ListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_CreateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).CreateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_CreateItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).CreateItem(ctx, req.(*CreateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_UpdateItemContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItemContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).UpdateItemContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_UpdateItemContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).UpdateItemContext(ctx, req.(*UpdateItemContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_AdvanceGate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdvanceGateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).AdvanceGate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_AdvanceGate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).AdvanceGate(ctx, req.(*AdvanceGateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_CloseItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).CloseItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_CloseItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).CloseItem(ctx, req.(*CloseItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeliveryService_ServiceDesc is the grpc.ServiceDesc for DeliveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeliveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iot.delivery.v1.DeliveryService",
	HandlerType: (*DeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDashboard",
			Handler:    _DeliveryService_GetDashboard_Handler,
		},
		{
			MethodName: "ListItems",
			Handler:    _DeliveryService_ListItems_Handler,
		},
		{
			MethodName: "CreateItem",
			Handler:    _DeliveryService_CreateItem_Handler,
		},
		{
			MethodName: "UpdateItemContext",
			Handler:    _DeliveryService_UpdateItemContext_Handler,
		},
		{
			MethodName: "AdvanceGate",
			Handler:    _DeliveryService_AdvanceGate_Handler,
		},
		{
			MethodName: "CloseItem",
			Handler:    _DeliveryService_CloseItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iot_delivery.proto",
}
