// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: iot_delivery.proto

package deliveryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	_ "yunka.io/pkg/contractdsl/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardRequest) Reset() {
	*x = GetDashboardRequest{}
	mi := &file_iot_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardRequest) ProtoMessage() {}

func (x *GetDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iot_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardRequest) Descriptor() ([]byte, []int) {
	return file_iot_delivery_proto_rawDescGZIP(), []int{0}
}

type GetDashboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dashboard     *Dashboard             `protobuf:"bytes,1,opt,name=dashboard,proto3" json:"dashboard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardResponse) Reset() {
	*x = GetDashboardResponse{}
	mi := &file_iot_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardResponse) ProtoMessage() {}

func (x *GetDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iot_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardResponse.ProtoReflect.Descriptor instead.
func (*GetDashboardResponse) Descriptor() ([]byte, []int) {
	return file_iot_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *GetDashboardResponse) GetDashboard() *Dashboard {
	if x != nil {
		return x.Dashboard
	}
	return nil
}

type ListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_iot_delivery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iot_delivery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_iot_delivery_proto_rawDescGZIP(), []int{2}
}

type ListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*WorkItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_iot_delivery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iot_delivery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_iot_delivery_proto_rawDescGZIP(), []int{3}
}

func (x *ListItemsResponse) GetItems() []*WorkItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type WorkItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *WorkItem              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkItemResponse) Reset() {
	*x = WorkItemResponse{}
	mi := &file_iot_delivery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkItemResponse) ProtoMessage() {}

func (x *WorkItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iot_delivery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkItemResponse.ProtoReflect.Descriptor instead.
func (*WorkItemResponse) Descriptor() ([]byte, []int) {
	return file_iot_delivery_proto_rawDescGZIP(), []int{4}
}

func (x *WorkItemResponse) GetItem() *WorkItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type Dashboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boards        []*BoardSummary        `protobuf:"bytes,1,rep,name=boards,proto3" json:"boards,omitempty"`
	Items         []*WorkItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dashboard) Reset() {
	*x = Dashboard{}
	mi := &file_iot_delivery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dashboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dashboard) ProtoMessage() {}

func (x *Dashboard) ProtoReflect() protoreflect.Message {
	mi := &file_iot_delivery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dashboard.ProtoReflect.Descriptor instead.
func (*Dashboard) Descriptor() ([]byte, []int) {
	return file_iot_delivery_proto_rawDescGZIP(), []int{5}
}

func (x *Dashboard) GetBoards() []*BoardSummary {
	if x != nil {
		return x.Boards
	}
	return nil
}

func (x *Dashboard) GetItems() []*WorkItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Dashboard) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

type BoardSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         string                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Active        int32                  `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Blocked       int32                  `protobuf:"varint,4,opt,name=blocked,proto3" json:"blocked,omitempty"`
	Verifying     int32                  `protobuf:"varint,5,opt,name=verifying,proto3" json:"verifying,omitempty"`
	Released      int32                  `protobuf:"varint,6,opt,name=released,proto3" json:"released,omitempty"`
	Closed        int32                  `protobuf:"varint,7,opt,name=closed,proto3" json:"closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardSummary) Reset() {
	*x = BoardSummary{}
	mi := &file_iot_delivery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardSummary) ProtoMessage() {}

func (x *BoardSummary) ProtoReflect() protoreflect.Message {
	mi := &file_iot_delivery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardSummary.ProtoReflect.Descriptor instead.
func (*BoardSummary) Descriptor() ([]byte, []int) {
	return file_iot_delivery_proto_rawDescGZIP(), []int{6}
}

func (x *BoardSummary) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *BoardSummary) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BoardSummary) GetActive() int32 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *BoardSummary) GetBlocked() int32 {
	if x != nil {
		return x.Blocked
	}
	return 0
}

func (x *BoardSummary) GetVerifying() int32 {
	if x != nil {
		return x.Verifying
	}
	return 0
}

func (x *BoardSummary) GetReleased() int32 {
	if x != nil {
		return x.Released
	}
	return 0
}

func (x *BoardSummary) GetClosed() int32 {
	if x != nil {
		return x.Closed
	}
	return 0
}

type WorkItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Board         string                 `protobuf:"bytes,3,opt,name=board,proto3" json:"board,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Owner         string                 `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	Priority      string                 `protobuf:"bytes,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Gate          string                 `protobuf:"bytes,8,opt,name=gate,proto3" json:"gate,omitempty"`
	DueDate       string                 `protobuf:"bytes,9,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	Plan          string                 `protobuf:"bytes,10,opt,name=plan,proto3" json:"plan,omitempty"`
	Solution      string                 `protobuf:"bytes,11,opt,name=solution,proto3" json:"solution,omitempty"`
	Decisions     []*Decision            `protobuf:"bytes,12,rep,name=decisions,proto3" json:"decisions,omitempty"`
	Evidence      []*Evidence            `protobuf:"bytes,13,rep,name=evidence,proto3" json:"evidence,omitempty"`
	Retrospective string                 `protobuf:"bytes,14,opt,name=retrospective,proto3" json:"retrospective,omitempty"`
	Blocker       string                 `protobuf:"bytes,15,opt,name=blocker,proto3" json:"blocker,omitempty"`
	IsSample      bool                   `protobuf:"varint,16,opt,name=is_sample,json=isSample,proto3" json:"is_sample,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkItem) Reset() {
	*x = WorkItem{}
	mi := &file_iot_delivery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkItem) ProtoMessage() {}

func (x *WorkItem) ProtoReflect() protoreflect.Message {
	mi := &file_iot_delivery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkItem.ProtoReflect.Descriptor instead.
func (*WorkItem) Descriptor() ([]byte, []int) {
	return file_iot_delivery_proto_rawDescGZIP(), []int{7}
}

func (x *WorkItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WorkItem) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *WorkItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WorkItem) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *WorkItem) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *WorkItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkItem) GetGate() string {
	if x != nil {
		return x.Gate
	}
	return ""
}

func (x *WorkItem) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *WorkItem) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *WorkItem) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *WorkItem) GetDecisions() []*Decision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

func (x *WorkItem) GetEvidence() []*Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *WorkItem) GetRetrospective() string {
	if x != nil {
		return x.Retrospective
	}
	return ""
}

func (x *WorkItem) GetBlocker() string {
	if x != nil {
		return x.Blocker
	}
	return ""
}

func (x *WorkItem) GetIsSample() bool {
	if x != nil {
		return x.IsSample
	}
	return false
}

func (x *WorkItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WorkItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Evidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Reference     string                 `protobuf:"bytes,3,opt,name=reference,proto3" json:"reference,omitempty"`
	RecordedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Evidence) Reset() {
	*x = Evidence{}
	mi := &file_iot_delivery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evidence) ProtoMessage() {}

func (x *Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_iot_delivery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evidence.ProtoReflect.Descriptor instead.
func (*Evidence) Descriptor() ([]byte, []int) {
	return file_iot_delivery_proto_rawDescGZIP(), []int{8}
}

func (x *Evidence) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Evidence) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Evidence) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *Evidence) GetRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordedAt
	}
	return nil
}

type Decision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	Outcome       string                 `protobuf:"bytes,4,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Consequences  string                 `protobuf:"bytes,5,opt,name=consequences,proto3" json:"consequences,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_iot_delivery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_iot_delivery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_iot_delivery_proto_rawDescGZIP(), []int{9}
}

func (x *Decision) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Decision) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Decision) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *Decision) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *Decision) GetConsequences() string {
	if x != nil {
		return x.Consequences
	}
	return ""
}

func (x *Decision) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Board         string                 `protobuf:"bytes,2,opt,name=board,proto3" json:"board,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Priority      string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	DueDate       string                 `protobuf:"bytes,6,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	Plan          string                 `protobuf:"bytes,7,opt,name=plan,proto3" json:"plan,omitempty"`
	Solution      string                 `protobuf:"bytes,8,opt,name=solution,proto3" json:"solution,omitempty"`
	IsSample      bool                   `protobuf:"varint,9,opt,name=is_sample,json=isSample,proto3" json:"is_sample,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_iot_delivery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iot_delivery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_iot_delivery_proto_rawDescGZIP(), []int{10}
}

func (x *CreateItemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateItemRequest) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *CreateItemRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateItemRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CreateItemRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *CreateItemRequest) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *CreateItemRequest) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *CreateItemRequest) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *CreateItemRequest) GetIsSample() bool {
	if x != nil {
		return x.IsSample
	}
	return false
}

type UpdateItemContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Plan          *string                `protobuf:"bytes,2,opt,name=plan,proto3,oneof" json:"plan,omitempty"`
	Solution      *string                `protobuf:"bytes,3,opt,name=solution,proto3,oneof" json:"solution,omitempty"`
	Blocker       *string                `protobuf:"bytes,4,opt,name=blocker,proto3,oneof" json:"blocker,omitempty"`
	Decision      *Decision              `protobuf:"bytes,5,opt,name=decision,proto3,oneof" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemContextRequest) Reset() {
	*x = UpdateItemContextRequest{}
	mi := &file_iot_delivery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemContextRequest) ProtoMessage() {}

func (x *UpdateItemContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iot_delivery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemContextRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemContextRequest) Descriptor() ([]byte, []int) {
	return file_iot_delivery_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateItemContextRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateItemContextRequest) GetPlan() string {
	if x != nil && x.Plan != nil {
		return *x.Plan
	}
	return ""
}

func (x *UpdateItemContextRequest) GetSolution() string {
	if x != nil && x.Solution != nil {
		return *x.Solution
	}
	return ""
}

func (x *UpdateItemContextRequest) GetBlocker() string {
	if x != nil && x.Blocker != nil {
		return *x.Blocker
	}
	return ""
}

func (x *UpdateItemContextRequest) GetDecision() *Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}

type AdvanceGateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Gate          string                 `protobuf:"bytes,2,opt,name=gate,proto3" json:"gate,omitempty"`
	Evidence      []*Evidence            `protobuf:"bytes,3,rep,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvanceGateRequest) Reset() {
	*x = AdvanceGateRequest{}
	mi := &file_iot_delivery_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvanceGateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvanceGateRequest) ProtoMessage() {}

func (x *AdvanceGateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iot_delivery_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvanceGateRequest.ProtoReflect.Descriptor instead.
func (*AdvanceGateRequest) Descriptor() ([]byte, []int) {
	return file_iot_delivery_proto_rawDescGZIP(), []int{12}
}

func (x *AdvanceGateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdvanceGateRequest) GetGate() string {
	if x != nil {
		return x.Gate
	}
	return ""
}

func (x *AdvanceGateRequest) GetEvidence() []*Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type CloseItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Retrospective string                 `protobuf:"bytes,2,opt,name=retrospective,proto3" json:"retrospective,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseItemRequest) Reset() {
	*x = CloseItemRequest{}
	mi := &file_iot_delivery_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseItemRequest) ProtoMessage() {}

func (x *CloseItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iot_delivery_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseItemRequest.ProtoReflect.Descriptor instead.
func (*CloseItemRequest) Descriptor() ([]byte, []int) {
	return file_iot_delivery_proto_rawDescGZIP(), []int{13}
}

func (x *CloseItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CloseItemRequest) GetRetrospective() string {
	if x != nil {
		return x.Retrospective
	}
	return ""
}

var File_iot_delivery_proto protoreflect.FileDescriptor

const file_iot_delivery_proto_rawDesc = "" +
	"\n" +
	"\x12iot_delivery.proto\x12\x0fiot.delivery.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ayunka/dsl/v1/options.proto\"\x1d\n" +
	"\x13GetDashboardRequest:\x06\xd2\xf3\x18\x02\b\x01\"X\n" +
	"\x14GetDashboardResponse\x128\n" +
	"\tdashboard\x18\x01 \x01(\v2\x1a.iot.delivery.v1.DashboardR\tdashboard:\x06\xd2\xf3\x18\x02\b\x02\"\x1a\n" +
	"\x10ListItemsRequest:\x06\xd2\xf3\x18\x02\b\x01\"L\n" +
	"\x11ListItemsResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.iot.delivery.v1.WorkItemR\x05items:\x06\xd2\xf3\x18\x02\b\x02\"I\n" +
	"\x10WorkItemResponse\x12-\n" +
	"\x04item\x18\x01 \x01(\v2\x19.iot.delivery.v1.WorkItemR\x04item:\x06\xd2\xf3\x18\x02\b\x02\"\xba\x01\n" +
	"\tDashboard\x125\n" +
	"\x06boards\x18\x01 \x03(\v2\x1d.iot.delivery.v1.BoardSummaryR\x06boards\x12/\n" +
	"\x05items\x18\x02 \x03(\v2\x19.iot.delivery.v1.WorkItemR\x05items\x12=\n" +
	"\fgenerated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt:\x06\xd2\xf3\x18\x02\b\x03\"\xc6\x01\n" +
	"\fBoardSummary\x12\x14\n" +
	"\x05board\x18\x01 \x01(\tR\x05board\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x16\n" +
	"\x06active\x18\x03 \x01(\x05R\x06active\x12\x18\n" +
	"\ablocked\x18\x04 \x01(\x05R\ablocked\x12\x1c\n" +
	"\tverifying\x18\x05 \x01(\x05R\tverifying\x12\x1a\n" +
	"\breleased\x18\x06 \x01(\x05R\breleased\x12\x16\n" +
	"\x06closed\x18\a \x01(\x05R\x06closed:\x06\xd2\xf3\x18\x02\b\x03\"\xce\x04\n" +
	"\bWorkItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05board\x18\x03 \x01(\tR\x05board\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05owner\x18\x05 \x01(\tR\x05owner\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\tR\bpriority\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x12\n" +
	"\x04gate\x18\b \x01(\tR\x04gate\x12\x19\n" +
	"\bdue_date\x18\t \x01(\tR\adueDate\x12\x12\n" +
	"\x04plan\x18\n" +
	" \x01(\tR\x04plan\x12\x1a\n" +
	"\bsolution\x18\v \x01(\tR\bsolution\x127\n" +
	"\tdecisions\x18\f \x03(\v2\x19.iot.delivery.v1.DecisionR\tdecisions\x125\n" +
	"\bevidence\x18\r \x03(\v2\x19.iot.delivery.v1.EvidenceR\bevidence\x12$\n" +
	"\rretrospective\x18\x0e \x01(\tR\rretrospective\x12\x18\n" +
	"\ablocker\x18\x0f \x01(\tR\ablocker\x12\x1b\n" +
	"\tis_sample\x18\x10 \x01(\bR\bisSample\x129\n" +
	"\n" +
	"created_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt:\x06\xd2\xf3\x18\x02\b\x03\"\x97\x01\n" +
	"\bEvidence\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1c\n" +
	"\treference\x18\x03 \x01(\tR\treference\x12;\n" +
	"\vrecorded_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"recordedAt:\x06\xd2\xf3\x18\x02\b\x03\"\xcb\x01\n" +
	"\bDecision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12\x18\n" +
	"\aoutcome\x18\x04 \x01(\tR\aoutcome\x12\"\n" +
	"\fconsequences\x18\x05 \x01(\tR\fconsequences\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt:\x06\xd2\xf3\x18\x02\b\x03\"\xf5\x01\n" +
	"\x11CreateItemRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05board\x18\x02 \x01(\tR\x05board\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x12\x19\n" +
	"\bdue_date\x18\x06 \x01(\tR\adueDate\x12\x12\n" +
	"\x04plan\x18\a \x01(\tR\x04plan\x12\x1a\n" +
	"\bsolution\x18\b \x01(\tR\bsolution\x12\x1b\n" +
	"\tis_sample\x18\t \x01(\bR\bisSample:\x06\xd2\xf3\x18\x02\b\x01\"\xf6\x01\n" +
	"\x18UpdateItemContextRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04plan\x18\x02 \x01(\tH\x00R\x04plan\x88\x01\x01\x12\x1f\n" +
	"\bsolution\x18\x03 \x01(\tH\x01R\bsolution\x88\x01\x01\x12\x1d\n" +
	"\ablocker\x18\x04 \x01(\tH\x02R\ablocker\x88\x01\x01\x12:\n" +
	"\bdecision\x18\x05 \x01(\v2\x19.iot.delivery.v1.DecisionH\x03R\bdecision\x88\x01\x01:\x06\xd2\xf3\x18\x02\b\x01B\a\n" +
	"\x05_planB\v\n" +
	"\t_solutionB\n" +
	"\n" +
	"\b_blockerB\v\n" +
	"\t_decision\"w\n" +
	"\x12AdvanceGateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04gate\x18\x02 \x01(\tR\x04gate\x125\n" +
	"\bevidence\x18\x03 \x03(\v2\x19.iot.delivery.v1.EvidenceR\bevidence:\x06\xd2\xf3\x18\x02\b\x01\"P\n" +
	"\x10CloseItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\rretrospective\x18\x02 \x01(\tR\rretrospective:\x06\xd2\xf3\x18\x02\b\x012\x94\b\n" +
	"\x0fDeliveryService\x12\xac\x01\n" +
	"\fGetDashboard\x12$.iot.delivery.v1.GetDashboardRequest\x1a%.iot.delivery.v1.GetDashboardResponse\"O\xe2\xf3\x18K\n" +
	"\x16delivery.dashboard.get\x12\rget_dashboard\x1a\x17delivery.dashboard.read2\x01\x02H\x01R\x04\b\x02\x10\x01\x12\x99\x01\n" +
	"\tListItems\x12!.iot.delivery.v1.ListItemsRequest\x1a\".iot.delivery.v1.ListItemsResponse\"E\xe2\xf3\x18A\n" +
	"\x13delivery.items.list\x12\n" +
	"list_items\x1a\x13delivery.items.read2\x01\x02H\x01R\x04\b\x02\x10\x01\x12\x9e\x01\n" +
	"\n" +
	"CreateItem\x12\".iot.delivery.v1.CreateItemRequest\x1a!.iot.delivery.v1.WorkItemResponse\"I\xe2\xf3\x18E\n" +
	"\x15delivery.items.create\x12\vcreate_item\x1a\x14delivery.items.write2\x01\x02H\x01R\x04\b\x03\x10\x01\x12\xbc\x01\n" +
	"\x11UpdateItemContext\x12).iot.delivery.v1.UpdateItemContextRequest\x1a!.iot.delivery.v1.WorkItemResponse\"Y\xe2\xf3\x18U\n" +
	"\x1ddelivery.items.update-context\x12\x13update_item_context\x1a\x14delivery.items.write2\x01\x02H\x01R\x04\b\x03\x10\x01\x12\xa6\x01\n" +
	"\vAdvanceGate\x12#.iot.delivery.v1.AdvanceGateRequest\x1a!.iot.delivery.v1.WorkItemResponse\"O\xe2\xf3\x18K\n" +
	"\x1bdelivery.items.advance-gate\x12\fadvance_gate\x1a\x13delivery.items.gate2\x01\x02H\x01R\x04\b\x03\x10\x01\x12\x9a\x01\n" +
	"\tCloseItem\x12!.iot.delivery.v1.CloseItemRequest\x1a!.iot.delivery.v1.WorkItemResponse\"G\xe2\xf3\x18C\n" +
	"\x14delivery.items.close\x12\n" +
	"close_item\x1a\x14delivery.items.close2\x01\x02H\x01R\x04\b\x03\x10\x01\x1a\x10\xda\xf3\x18\f\n" +
	"\n" +
	"managementBj\xca\xf3\x18\x0e\n" +
	"\bdelivery\x12\x02v1ZVgithub.com/hvritual/iot-delivery-system/backend-yunka/contracts/delivery/v1;deliveryv1b\x06proto3"

var (
	file_iot_delivery_proto_rawDescOnce sync.Once
	file_iot_delivery_proto_rawDescData []byte
)

func file_iot_delivery_proto_rawDescGZIP() []byte {
	file_iot_delivery_proto_rawDescOnce.Do(func() {
		file_iot_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iot_delivery_proto_rawDesc), len(file_iot_delivery_proto_rawDesc)))
	})
	return file_iot_delivery_proto_rawDescData
}

var file_iot_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_iot_delivery_proto_goTypes = []any{
	(*GetDashboardRequest)(nil),      // 0: iot.delivery.v1.GetDashboardRequest
	(*GetDashboardResponse)(nil),     // 1: iot.delivery.v1.GetDashboardResponse
	(*ListItemsRequest)(nil),         // 2: iot.delivery.v1.ListItemsRequest
	(*ListItemsResponse)(nil),        // 3: iot.delivery.v1.ListItemsResponse
	(*WorkItemResponse)(nil),         // 4: iot.delivery.v1.WorkItemResponse
	(*Dashboard)(nil),                // 5: iot.delivery.v1.Dashboard
	(*BoardSummary)(nil),             // 6: iot.delivery.v1.BoardSummary
	(*WorkItem)(nil),                 // 7: iot.delivery.v1.WorkItem
	(*Evidence)(nil),                 // 8: iot.delivery.v1.Evidence
	(*Decision)(nil),                 // 9: iot.delivery.v1.Decision
	(*CreateItemRequest)(nil),        // 10: iot.delivery.v1.CreateItemRequest
	(*UpdateItemContextRequest)(nil), // 11: iot.delivery.v1.UpdateItemContextRequest
	(*AdvanceGateRequest)(nil),       // 12: iot.delivery.v1.AdvanceGateRequest
	(*CloseItemRequest)(nil),         // 13: iot.delivery.v1.CloseItemRequest
	(*timestamppb.Timestamp)(nil),    // 14: google.protobuf.Timestamp
}
var file_iot_delivery_proto_depIdxs = []int32{
	5,  // 0: iot.delivery.v1.GetDashboardResponse.dashboard:type_name -> iot.delivery.v1.Dashboard
	7,  // 1: iot.delivery.v1.ListItemsResponse.items:type_name -> iot.delivery.v1.WorkItem
	7,  // 2: iot.delivery.v1.WorkItemResponse.item:type_name -> iot.delivery.v1.WorkItem
	6,  // 3: iot.delivery.v1.Dashboard.boards:type_name -> iot.delivery.v1.BoardSummary
	7,  // 4: iot.delivery.v1.Dashboard.items:type_name -> iot.delivery.v1.WorkItem
	14, // 5: iot.delivery.v1.Dashboard.generated_at:type_name -> google.protobuf.Timestamp
	9,  // 6: iot.delivery.v1.WorkItem.decisions:type_name -> iot.delivery.v1.Decision
	8,  // 7: iot.delivery.v1.WorkItem.evidence:type_name -> iot.delivery.v1.Evidence
	14, // 8: iot.delivery.v1.WorkItem.created_at:type_name -> google.protobuf.Timestamp
	14, // 9: iot.delivery.v1.WorkItem.updated_at:type_name -> google.protobuf.Timestamp
	14, // 10: iot.delivery.v1.Evidence.recorded_at:type_name -> google.protobuf.Timestamp
	14, // 11: iot.delivery.v1.Decision.created_at:type_name -> google.protobuf.Timestamp
	9,  // 12: iot.delivery.v1.UpdateItemContextRequest.decision:type_name -> iot.delivery.v1.Decision
	8,  // 13: iot.delivery.v1.AdvanceGateRequest.evidence:type_name -> iot.delivery.v1.Evidence
	0,  // 14: iot.delivery.v1.DeliveryService.GetDashboard:input_type -> iot.delivery.v1.GetDashboardRequest
	2,  // 15: iot.delivery.v1.DeliveryService.ListItems:input_type -> iot.delivery.v1.ListItemsRequest
	10, // 16: iot.delivery.v1.DeliveryService.CreateItem:input_type -> iot.delivery.v1.CreateItemRequest
	11, // 17: iot.delivery.v1.DeliveryService.UpdateItemContext:input_type -> iot.delivery.v1.UpdateItemContextRequest
	12, // 18: iot.delivery.v1.DeliveryService.AdvanceGate:input_type -> iot.delivery.v1.AdvanceGateRequest
	13, // 19: iot.delivery.v1.DeliveryService.CloseItem:input_type -> iot.delivery.v1.CloseItemRequest
	1,  // 20: iot.delivery.v1.DeliveryService.GetDashboard:output_type -> iot.delivery.v1.GetDashboardResponse
	3,  // 21: iot.delivery.v1.DeliveryService.ListItems:output_type -> iot.delivery.v1.ListItemsResponse
	4,  // 22: iot.delivery.v1.DeliveryService.CreateItem:output_type -> iot.delivery.v1.WorkItemResponse
	4,  // 23: iot.delivery.v1.DeliveryService.UpdateItemContext:output_type -> iot.delivery.v1.WorkItemResponse
	4,  // 24: iot.delivery.v1.DeliveryService.AdvanceGate:output_type -> iot.delivery.v1.WorkItemResponse
	4,  // 25: iot.delivery.v1.DeliveryService.CloseItem:output_type -> iot.delivery.v1.WorkItemResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_iot_delivery_proto_init() }
func file_iot_delivery_proto_init() {
	if File_iot_delivery_proto != nil {
		return
	}
	file_iot_delivery_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iot_delivery_proto_rawDesc), len(file_iot_delivery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iot_delivery_proto_goTypes,
		DependencyIndexes: file_iot_delivery_proto_depIdxs,
		MessageInfos:      file_iot_delivery_proto_msgTypes,
	}.Build()
	File_iot_delivery_proto = out.File
	file_iot_delivery_proto_goTypes = nil
	file_iot_delivery_proto_depIdxs = nil
}
