// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: delivery/v1/notification.proto

package deliveryv1

import (
	_ "github.com/hvritual/yunka.io/pkg/contractdsl/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListNotificationsRequest intentionally carries no caller-controlled project
// scope. Durable grants determine which project subjects are visible.
type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_delivery_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *ListNotificationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_delivery_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *ListNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	DeliveredAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_delivery_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_delivery_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *Notification) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *Notification) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Notification) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Notification) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Notification) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *Notification) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

var File_delivery_v1_notification_proto protoreflect.FileDescriptor

const file_delivery_v1_notification_proto_rawDesc = "" +
	"\n" +
	"\x1edelivery/v1/notification.proto\x12\x0fiot.delivery.v1\x1a\x1ayunka/dsl/v1/options.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"8\n" +
	"\x18ListNotificationsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit:\x06\xd2\xf3\x18\x02\b\x01\"h\n" +
	"\x19ListNotificationsResponse\x12C\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1d.iot.delivery.v1.NotificationR\rnotifications:\x06\xd2\xf3\x18\x02\b\x02\"\xb0\x02\n" +
	"\fNotification\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x12;\n" +
	"\voccurred_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12=\n" +
	"\fdelivered_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vdeliveredAt:\x06\xd2\xf3\x18\x02\b\x03BXZVgithub.com/hvritual/iot-delivery-system/backend-yunka/contracts/delivery/v1;deliveryv1b\x06proto3"

var (
	file_delivery_v1_notification_proto_rawDescOnce sync.Once
	file_delivery_v1_notification_proto_rawDescData []byte
)

func file_delivery_v1_notification_proto_rawDescGZIP() []byte {
	file_delivery_v1_notification_proto_rawDescOnce.Do(func() {
		file_delivery_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delivery_v1_notification_proto_rawDesc), len(file_delivery_v1_notification_proto_rawDesc)))
	})
	return file_delivery_v1_notification_proto_rawDescData
}

var file_delivery_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_delivery_v1_notification_proto_goTypes = []any{
	(*ListNotificationsRequest)(nil),  // 0: iot.delivery.v1.ListNotificationsRequest
	(*ListNotificationsResponse)(nil), // 1: iot.delivery.v1.ListNotificationsResponse
	(*Notification)(nil),              // 2: iot.delivery.v1.Notification
	(*timestamppb.Timestamp)(nil),     // 3: google.protobuf.Timestamp
}
var file_delivery_v1_notification_proto_depIdxs = []int32{
	2, // 0: iot.delivery.v1.ListNotificationsResponse.notifications:type_name -> iot.delivery.v1.Notification
	3, // 1: iot.delivery.v1.Notification.occurred_at:type_name -> google.protobuf.Timestamp
	3, // 2: iot.delivery.v1.Notification.delivered_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_delivery_v1_notification_proto_init() }
func file_delivery_v1_notification_proto_init() {
	if File_delivery_v1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delivery_v1_notification_proto_rawDesc), len(file_delivery_v1_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_delivery_v1_notification_proto_goTypes,
		DependencyIndexes: file_delivery_v1_notification_proto_depIdxs,
		MessageInfos:      file_delivery_v1_notification_proto_msgTypes,
	}.Build()
	File_delivery_v1_notification_proto = out.File
	file_delivery_v1_notification_proto_goTypes = nil
	file_delivery_v1_notification_proto_depIdxs = nil
}
