// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: delivery/v1/planning.proto

package deliveryv1

import (
	_ "github.com/hvritual/yunka.io/pkg/contractdsl/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Release       *Release               `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_delivery_v1_planning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_planning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_planning_proto_rawDescGZIP(), []int{0}
}

func (x *ReleaseResponse) GetRelease() *Release {
	if x != nil {
		return x.Release
	}
	return nil
}

type SprintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sprint        *Sprint                `protobuf:"bytes,1,opt,name=sprint,proto3" json:"sprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SprintResponse) Reset() {
	*x = SprintResponse{}
	mi := &file_delivery_v1_planning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SprintResponse) ProtoMessage() {}

func (x *SprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_planning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SprintResponse.ProtoReflect.Descriptor instead.
func (*SprintResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_planning_proto_rawDescGZIP(), []int{1}
}

func (x *SprintResponse) GetSprint() *Sprint {
	if x != nil {
		return x.Sprint
	}
	return nil
}

type MilestoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Milestone     *Milestone             `protobuf:"bytes,1,opt,name=milestone,proto3" json:"milestone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MilestoneResponse) Reset() {
	*x = MilestoneResponse{}
	mi := &file_delivery_v1_planning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MilestoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MilestoneResponse) ProtoMessage() {}

func (x *MilestoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_planning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MilestoneResponse.ProtoReflect.Descriptor instead.
func (*MilestoneResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_planning_proto_rawDescGZIP(), []int{2}
}

func (x *MilestoneResponse) GetMilestone() *Milestone {
	if x != nil {
		return x.Milestone
	}
	return nil
}

type Release struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	TargetDate    string                 `protobuf:"bytes,5,opt,name=target_date,json=targetDate,proto3" json:"target_date,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Release) Reset() {
	*x = Release{}
	mi := &file_delivery_v1_planning_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Release) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Release) ProtoMessage() {}

func (x *Release) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_planning_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Release.ProtoReflect.Descriptor instead.
func (*Release) Descriptor() ([]byte, []int) {
	return file_delivery_v1_planning_proto_rawDescGZIP(), []int{3}
}

func (x *Release) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Release) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Release) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Release) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Release) GetTargetDate() string {
	if x != nil {
		return x.TargetDate
	}
	return ""
}

func (x *Release) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Release) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Release) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Release) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Sprint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Goal          string                 `protobuf:"bytes,4,opt,name=goal,proto3" json:"goal,omitempty"`
	StartDate     string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sprint) Reset() {
	*x = Sprint{}
	mi := &file_delivery_v1_planning_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sprint) ProtoMessage() {}

func (x *Sprint) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_planning_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sprint.ProtoReflect.Descriptor instead.
func (*Sprint) Descriptor() ([]byte, []int) {
	return file_delivery_v1_planning_proto_rawDescGZIP(), []int{4}
}

func (x *Sprint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Sprint) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Sprint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sprint) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *Sprint) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Sprint) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Sprint) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Sprint) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Sprint) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Milestone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	TargetDate    string                 `protobuf:"bytes,4,opt,name=target_date,json=targetDate,proto3" json:"target_date,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Milestone) Reset() {
	*x = Milestone{}
	mi := &file_delivery_v1_planning_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Milestone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Milestone) ProtoMessage() {}

func (x *Milestone) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_planning_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Milestone.ProtoReflect.Descriptor instead.
func (*Milestone) Descriptor() ([]byte, []int) {
	return file_delivery_v1_planning_proto_rawDescGZIP(), []int{5}
}

func (x *Milestone) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Milestone) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Milestone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Milestone) GetTargetDate() string {
	if x != nil {
		return x.TargetDate
	}
	return ""
}

func (x *Milestone) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Milestone) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Milestone) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Milestone) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	TargetDate    string                 `protobuf:"bytes,4,opt,name=target_date,json=targetDate,proto3" json:"target_date,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReleaseRequest) Reset() {
	*x = CreateReleaseRequest{}
	mi := &file_delivery_v1_planning_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReleaseRequest) ProtoMessage() {}

func (x *CreateReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_planning_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReleaseRequest.ProtoReflect.Descriptor instead.
func (*CreateReleaseRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_planning_proto_rawDescGZIP(), []int{6}
}

func (x *CreateReleaseRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateReleaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateReleaseRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateReleaseRequest) GetTargetDate() string {
	if x != nil {
		return x.TargetDate
	}
	return ""
}

func (x *CreateReleaseRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateReleaseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateSprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Goal          string                 `protobuf:"bytes,3,opt,name=goal,proto3" json:"goal,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSprintRequest) Reset() {
	*x = CreateSprintRequest{}
	mi := &file_delivery_v1_planning_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSprintRequest) ProtoMessage() {}

func (x *CreateSprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_planning_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSprintRequest.ProtoReflect.Descriptor instead.
func (*CreateSprintRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_planning_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSprintRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateSprintRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSprintRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *CreateSprintRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateSprintRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *CreateSprintRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateMilestoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TargetDate    string                 `protobuf:"bytes,3,opt,name=target_date,json=targetDate,proto3" json:"target_date,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMilestoneRequest) Reset() {
	*x = CreateMilestoneRequest{}
	mi := &file_delivery_v1_planning_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMilestoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMilestoneRequest) ProtoMessage() {}

func (x *CreateMilestoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_planning_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMilestoneRequest.ProtoReflect.Descriptor instead.
func (*CreateMilestoneRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_planning_proto_rawDescGZIP(), []int{8}
}

func (x *CreateMilestoneRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateMilestoneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMilestoneRequest) GetTargetDate() string {
	if x != nil {
		return x.TargetDate
	}
	return ""
}

func (x *CreateMilestoneRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateMilestoneRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListReleasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReleasesRequest) Reset() {
	*x = ListReleasesRequest{}
	mi := &file_delivery_v1_planning_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReleasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReleasesRequest) ProtoMessage() {}

func (x *ListReleasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_planning_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReleasesRequest.ProtoReflect.Descriptor instead.
func (*ListReleasesRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_planning_proto_rawDescGZIP(), []int{9}
}

func (x *ListReleasesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListReleasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Releases      []*Release             `protobuf:"bytes,1,rep,name=releases,proto3" json:"releases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReleasesResponse) Reset() {
	*x = ListReleasesResponse{}
	mi := &file_delivery_v1_planning_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReleasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReleasesResponse) ProtoMessage() {}

func (x *ListReleasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_planning_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReleasesResponse.ProtoReflect.Descriptor instead.
func (*ListReleasesResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_planning_proto_rawDescGZIP(), []int{10}
}

func (x *ListReleasesResponse) GetReleases() []*Release {
	if x != nil {
		return x.Releases
	}
	return nil
}

type ListSprintsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSprintsRequest) Reset() {
	*x = ListSprintsRequest{}
	mi := &file_delivery_v1_planning_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSprintsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSprintsRequest) ProtoMessage() {}

func (x *ListSprintsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_planning_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSprintsRequest.ProtoReflect.Descriptor instead.
func (*ListSprintsRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_planning_proto_rawDescGZIP(), []int{11}
}

func (x *ListSprintsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListSprintsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sprints       []*Sprint              `protobuf:"bytes,1,rep,name=sprints,proto3" json:"sprints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSprintsResponse) Reset() {
	*x = ListSprintsResponse{}
	mi := &file_delivery_v1_planning_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSprintsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSprintsResponse) ProtoMessage() {}

func (x *ListSprintsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_planning_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSprintsResponse.ProtoReflect.Descriptor instead.
func (*ListSprintsResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_planning_proto_rawDescGZIP(), []int{12}
}

func (x *ListSprintsResponse) GetSprints() []*Sprint {
	if x != nil {
		return x.Sprints
	}
	return nil
}

type ListMilestonesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMilestonesRequest) Reset() {
	*x = ListMilestonesRequest{}
	mi := &file_delivery_v1_planning_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMilestonesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMilestonesRequest) ProtoMessage() {}

func (x *ListMilestonesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_planning_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMilestonesRequest.ProtoReflect.Descriptor instead.
func (*ListMilestonesRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_planning_proto_rawDescGZIP(), []int{13}
}

func (x *ListMilestonesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListMilestonesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Milestones    []*Milestone           `protobuf:"bytes,1,rep,name=milestones,proto3" json:"milestones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMilestonesResponse) Reset() {
	*x = ListMilestonesResponse{}
	mi := &file_delivery_v1_planning_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMilestonesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMilestonesResponse) ProtoMessage() {}

func (x *ListMilestonesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_planning_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMilestonesResponse.ProtoReflect.Descriptor instead.
func (*ListMilestonesResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_planning_proto_rawDescGZIP(), []int{14}
}

func (x *ListMilestonesResponse) GetMilestones() []*Milestone {
	if x != nil {
		return x.Milestones
	}
	return nil
}

var File_delivery_v1_planning_proto protoreflect.FileDescriptor

const file_delivery_v1_planning_proto_rawDesc = "" +
	"\n" +
	"\x1adelivery/v1/planning.proto\x12\x0fiot.delivery.v1\x1a\x1ayunka/dsl/v1/options.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"M\n" +
	"\x0fReleaseResponse\x122\n" +
	"\arelease\x18\x01 \x01(\v2\x18.iot.delivery.v1.ReleaseR\arelease:\x06\xd2\xf3\x18\x02\b\x02\"I\n" +
	"\x0eSprintResponse\x12/\n" +
	"\x06sprint\x18\x01 \x01(\v2\x17.iot.delivery.v1.SprintR\x06sprint:\x06\xd2\xf3\x18\x02\b\x02\"U\n" +
	"\x11MilestoneResponse\x128\n" +
	"\tmilestone\x18\x01 \x01(\v2\x1a.iot.delivery.v1.MilestoneR\tmilestone:\x06\xd2\xf3\x18\x02\b\x02\"\xbf\x02\n" +
	"\aRelease\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1f\n" +
	"\vtarget_date\x18\x05 \x01(\tR\n" +
	"targetDate\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt:\x06\xd2\xf3\x18\x02\b\x03\"\xaf\x02\n" +
	"\x06Sprint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04goal\x18\x04 \x01(\tR\x04goal\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt:\x06\xd2\xf3\x18\x02\b\x03\"\xa7\x02\n" +
	"\tMilestone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vtarget_date\x18\x04 \x01(\tR\n" +
	"targetDate\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt:\x06\xd2\xf3\x18\x02\b\x03\"\xc6\x01\n" +
	"\x14CreateReleaseRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1f\n" +
	"\vtarget_date\x18\x04 \x01(\tR\n" +
	"targetDate\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription:\x06\xd2\xf3\x18\x02\b\x01\"\xb6\x01\n" +
	"\x13CreateSprintRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04goal\x18\x03 \x01(\tR\x04goal\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status:\x06\xd2\xf3\x18\x02\b\x01\"\xae\x01\n" +
	"\x16CreateMilestoneRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vtarget_date\x18\x03 \x01(\tR\n" +
	"targetDate\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription:\x06\xd2\xf3\x18\x02\b\x01\"<\n" +
	"\x13ListReleasesRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId:\x06\xd2\xf3\x18\x02\b\x01\"T\n" +
	"\x14ListReleasesResponse\x124\n" +
	"\breleases\x18\x01 \x03(\v2\x18.iot.delivery.v1.ReleaseR\breleases:\x06\xd2\xf3\x18\x02\b\x02\";\n" +
	"\x12ListSprintsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId:\x06\xd2\xf3\x18\x02\b\x01\"P\n" +
	"\x13ListSprintsResponse\x121\n" +
	"\asprints\x18\x01 \x03(\v2\x17.iot.delivery.v1.SprintR\asprints:\x06\xd2\xf3\x18\x02\b\x02\">\n" +
	"\x15ListMilestonesRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId:\x06\xd2\xf3\x18\x02\b\x01\"\\\n" +
	"\x16ListMilestonesResponse\x12:\n" +
	"\n" +
	"milestones\x18\x01 \x03(\v2\x1a.iot.delivery.v1.MilestoneR\n" +
	"milestones:\x06\xd2\xf3\x18\x02\b\x02BXZVgithub.com/hvritual/iot-delivery-system/backend-yunka/contracts/delivery/v1;deliveryv1b\x06proto3"

var (
	file_delivery_v1_planning_proto_rawDescOnce sync.Once
	file_delivery_v1_planning_proto_rawDescData []byte
)

func file_delivery_v1_planning_proto_rawDescGZIP() []byte {
	file_delivery_v1_planning_proto_rawDescOnce.Do(func() {
		file_delivery_v1_planning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delivery_v1_planning_proto_rawDesc), len(file_delivery_v1_planning_proto_rawDesc)))
	})
	return file_delivery_v1_planning_proto_rawDescData
}

var file_delivery_v1_planning_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_delivery_v1_planning_proto_goTypes = []any{
	(*ReleaseResponse)(nil),        // 0: iot.delivery.v1.ReleaseResponse
	(*SprintResponse)(nil),         // 1: iot.delivery.v1.SprintResponse
	(*MilestoneResponse)(nil),      // 2: iot.delivery.v1.MilestoneResponse
	(*Release)(nil),                // 3: iot.delivery.v1.Release
	(*Sprint)(nil),                 // 4: iot.delivery.v1.Sprint
	(*Milestone)(nil),              // 5: iot.delivery.v1.Milestone
	(*CreateReleaseRequest)(nil),   // 6: iot.delivery.v1.CreateReleaseRequest
	(*CreateSprintRequest)(nil),    // 7: iot.delivery.v1.CreateSprintRequest
	(*CreateMilestoneRequest)(nil), // 8: iot.delivery.v1.CreateMilestoneRequest
	(*ListReleasesRequest)(nil),    // 9: iot.delivery.v1.ListReleasesRequest
	(*ListReleasesResponse)(nil),   // 10: iot.delivery.v1.ListReleasesResponse
	(*ListSprintsRequest)(nil),     // 11: iot.delivery.v1.ListSprintsRequest
	(*ListSprintsResponse)(nil),    // 12: iot.delivery.v1.ListSprintsResponse
	(*ListMilestonesRequest)(nil),  // 13: iot.delivery.v1.ListMilestonesRequest
	(*ListMilestonesResponse)(nil), // 14: iot.delivery.v1.ListMilestonesResponse
	(*timestamppb.Timestamp)(nil),  // 15: google.protobuf.Timestamp
}
var file_delivery_v1_planning_proto_depIdxs = []int32{
	3,  // 0: iot.delivery.v1.ReleaseResponse.release:type_name -> iot.delivery.v1.Release
	4,  // 1: iot.delivery.v1.SprintResponse.sprint:type_name -> iot.delivery.v1.Sprint
	5,  // 2: iot.delivery.v1.MilestoneResponse.milestone:type_name -> iot.delivery.v1.Milestone
	15, // 3: iot.delivery.v1.Release.created_at:type_name -> google.protobuf.Timestamp
	15, // 4: iot.delivery.v1.Release.updated_at:type_name -> google.protobuf.Timestamp
	15, // 5: iot.delivery.v1.Sprint.created_at:type_name -> google.protobuf.Timestamp
	15, // 6: iot.delivery.v1.Sprint.updated_at:type_name -> google.protobuf.Timestamp
	15, // 7: iot.delivery.v1.Milestone.created_at:type_name -> google.protobuf.Timestamp
	15, // 8: iot.delivery.v1.Milestone.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 9: iot.delivery.v1.ListReleasesResponse.releases:type_name -> iot.delivery.v1.Release
	4,  // 10: iot.delivery.v1.ListSprintsResponse.sprints:type_name -> iot.delivery.v1.Sprint
	5,  // 11: iot.delivery.v1.ListMilestonesResponse.milestones:type_name -> iot.delivery.v1.Milestone
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_delivery_v1_planning_proto_init() }
func file_delivery_v1_planning_proto_init() {
	if File_delivery_v1_planning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delivery_v1_planning_proto_rawDesc), len(file_delivery_v1_planning_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_delivery_v1_planning_proto_goTypes,
		DependencyIndexes: file_delivery_v1_planning_proto_depIdxs,
		MessageInfos:      file_delivery_v1_planning_proto_msgTypes,
	}.Build()
	File_delivery_v1_planning_proto = out.File
	file_delivery_v1_planning_proto_goTypes = nil
	file_delivery_v1_planning_proto_depIdxs = nil
}
