// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: delivery/v1/project.proto

package deliveryv1

import (
	_ "github.com/hvritual/yunka.io/pkg/contractdsl/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectResponse) Reset() {
	*x = ProjectResponse{}
	mi := &file_delivery_v1_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectResponse) ProtoMessage() {}

func (x *ProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectResponse.ProtoReflect.Descriptor instead.
func (*ProjectResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_project_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Board         string                 `protobuf:"bytes,3,opt,name=board,proto3" json:"board,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_delivery_v1_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_delivery_v1_project_proto_rawDescGZIP(), []int{1}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *Project) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Project) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Project) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Board         string                 `protobuf:"bytes,2,opt,name=board,proto3" json:"board,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_delivery_v1_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_project_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *CreateProjectRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CreateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ListProjectsRequest intentionally carries no caller-controlled scope. The
// authenticated principal and durable grants determine the visible projects.
type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_delivery_v1_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_project_proto_rawDescGZIP(), []int{3}
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_delivery_v1_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_project_proto_rawDescGZIP(), []int{4}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type GetProjectProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectProgressRequest) Reset() {
	*x = GetProjectProgressRequest{}
	mi := &file_delivery_v1_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectProgressRequest) ProtoMessage() {}

func (x *GetProjectProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectProgressRequest.ProtoReflect.Descriptor instead.
func (*GetProjectProgressRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_project_proto_rawDescGZIP(), []int{5}
}

func (x *GetProjectProgressRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ProjectProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      *ProjectProgress       `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectProgressResponse) Reset() {
	*x = ProjectProgressResponse{}
	mi := &file_delivery_v1_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectProgressResponse) ProtoMessage() {}

func (x *ProjectProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectProgressResponse.ProtoReflect.Descriptor instead.
func (*ProjectProgressResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_project_proto_rawDescGZIP(), []int{6}
}

func (x *ProjectProgressResponse) GetProgress() *ProjectProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type ProjectProgress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProjectId       string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TotalItems      int32                  `protobuf:"varint,2,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	CompletedItems  int32                  `protobuf:"varint,3,opt,name=completed_items,json=completedItems,proto3" json:"completed_items,omitempty"`
	TotalWeight     float64                `protobuf:"fixed64,4,opt,name=total_weight,json=totalWeight,proto3" json:"total_weight,omitempty"`
	CompletedWeight float64                `protobuf:"fixed64,5,opt,name=completed_weight,json=completedWeight,proto3" json:"completed_weight,omitempty"`
	ProgressPercent float64                `protobuf:"fixed64,6,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProjectProgress) Reset() {
	*x = ProjectProgress{}
	mi := &file_delivery_v1_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectProgress) ProtoMessage() {}

func (x *ProjectProgress) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectProgress.ProtoReflect.Descriptor instead.
func (*ProjectProgress) Descriptor() ([]byte, []int) {
	return file_delivery_v1_project_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectProgress) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectProgress) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *ProjectProgress) GetCompletedItems() int32 {
	if x != nil {
		return x.CompletedItems
	}
	return 0
}

func (x *ProjectProgress) GetTotalWeight() float64 {
	if x != nil {
		return x.TotalWeight
	}
	return 0
}

func (x *ProjectProgress) GetCompletedWeight() float64 {
	if x != nil {
		return x.CompletedWeight
	}
	return 0
}

func (x *ProjectProgress) GetProgressPercent() float64 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

type GetProjectScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectScheduleRequest) Reset() {
	*x = GetProjectScheduleRequest{}
	mi := &file_delivery_v1_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectScheduleRequest) ProtoMessage() {}

func (x *GetProjectScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectScheduleRequest.ProtoReflect.Descriptor instead.
func (*GetProjectScheduleRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_project_proto_rawDescGZIP(), []int{8}
}

func (x *GetProjectScheduleRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ProjectScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedule      *ProjectSchedule       `protobuf:"bytes,1,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectScheduleResponse) Reset() {
	*x = ProjectScheduleResponse{}
	mi := &file_delivery_v1_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectScheduleResponse) ProtoMessage() {}

func (x *ProjectScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectScheduleResponse.ProtoReflect.Descriptor instead.
func (*ProjectScheduleResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_project_proto_rawDescGZIP(), []int{9}
}

func (x *ProjectScheduleResponse) GetSchedule() *ProjectSchedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

type ProjectSchedule struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ProjectId              string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	AsOfDate               string                 `protobuf:"bytes,2,opt,name=as_of_date,json=asOfDate,proto3" json:"as_of_date,omitempty"`
	TotalItems             int32                  `protobuf:"varint,3,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	ScheduledItems         int32                  `protobuf:"varint,4,opt,name=scheduled_items,json=scheduledItems,proto3" json:"scheduled_items,omitempty"`
	UnscheduledItems       int32                  `protobuf:"varint,5,opt,name=unscheduled_items,json=unscheduledItems,proto3" json:"unscheduled_items,omitempty"`
	BlockedItems           int32                  `protobuf:"varint,6,opt,name=blocked_items,json=blockedItems,proto3" json:"blocked_items,omitempty"`
	OverdueItems           int32                  `protobuf:"varint,7,opt,name=overdue_items,json=overdueItems,proto3" json:"overdue_items,omitempty"`
	DependencyBlockedItems int32                  `protobuf:"varint,8,opt,name=dependency_blocked_items,json=dependencyBlockedItems,proto3" json:"dependency_blocked_items,omitempty"`
	Capacity               []*OwnerCapacity       `protobuf:"bytes,9,rep,name=capacity,proto3" json:"capacity,omitempty"`
	Risks                  []*ScheduleRisk        `protobuf:"bytes,10,rep,name=risks,proto3" json:"risks,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProjectSchedule) Reset() {
	*x = ProjectSchedule{}
	mi := &file_delivery_v1_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSchedule) ProtoMessage() {}

func (x *ProjectSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSchedule.ProtoReflect.Descriptor instead.
func (*ProjectSchedule) Descriptor() ([]byte, []int) {
	return file_delivery_v1_project_proto_rawDescGZIP(), []int{10}
}

func (x *ProjectSchedule) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectSchedule) GetAsOfDate() string {
	if x != nil {
		return x.AsOfDate
	}
	return ""
}

func (x *ProjectSchedule) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *ProjectSchedule) GetScheduledItems() int32 {
	if x != nil {
		return x.ScheduledItems
	}
	return 0
}

func (x *ProjectSchedule) GetUnscheduledItems() int32 {
	if x != nil {
		return x.UnscheduledItems
	}
	return 0
}

func (x *ProjectSchedule) GetBlockedItems() int32 {
	if x != nil {
		return x.BlockedItems
	}
	return 0
}

func (x *ProjectSchedule) GetOverdueItems() int32 {
	if x != nil {
		return x.OverdueItems
	}
	return 0
}

func (x *ProjectSchedule) GetDependencyBlockedItems() int32 {
	if x != nil {
		return x.DependencyBlockedItems
	}
	return 0
}

func (x *ProjectSchedule) GetCapacity() []*OwnerCapacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *ProjectSchedule) GetRisks() []*ScheduleRisk {
	if x != nil {
		return x.Risks
	}
	return nil
}

type OwnerCapacity struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Owner                   string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	ItemCount               int32                  `protobuf:"varint,2,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	BlockedItems            int32                  `protobuf:"varint,3,opt,name=blocked_items,json=blockedItems,proto3" json:"blocked_items,omitempty"`
	OverdueItems            int32                  `protobuf:"varint,4,opt,name=overdue_items,json=overdueItems,proto3" json:"overdue_items,omitempty"`
	TotalEstimatePoints     float64                `protobuf:"fixed64,5,opt,name=total_estimate_points,json=totalEstimatePoints,proto3" json:"total_estimate_points,omitempty"`
	CompletedEstimatePoints float64                `protobuf:"fixed64,6,opt,name=completed_estimate_points,json=completedEstimatePoints,proto3" json:"completed_estimate_points,omitempty"`
	RemainingEstimatePoints float64                `protobuf:"fixed64,7,opt,name=remaining_estimate_points,json=remainingEstimatePoints,proto3" json:"remaining_estimate_points,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OwnerCapacity) Reset() {
	*x = OwnerCapacity{}
	mi := &file_delivery_v1_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnerCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnerCapacity) ProtoMessage() {}

func (x *OwnerCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnerCapacity.ProtoReflect.Descriptor instead.
func (*OwnerCapacity) Descriptor() ([]byte, []int) {
	return file_delivery_v1_project_proto_rawDescGZIP(), []int{11}
}

func (x *OwnerCapacity) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *OwnerCapacity) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *OwnerCapacity) GetBlockedItems() int32 {
	if x != nil {
		return x.BlockedItems
	}
	return 0
}

func (x *OwnerCapacity) GetOverdueItems() int32 {
	if x != nil {
		return x.OverdueItems
	}
	return 0
}

func (x *OwnerCapacity) GetTotalEstimatePoints() float64 {
	if x != nil {
		return x.TotalEstimatePoints
	}
	return 0
}

func (x *OwnerCapacity) GetCompletedEstimatePoints() float64 {
	if x != nil {
		return x.CompletedEstimatePoints
	}
	return 0
}

func (x *OwnerCapacity) GetRemainingEstimatePoints() float64 {
	if x != nil {
		return x.RemainingEstimatePoints
	}
	return 0
}

type ScheduleRisk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	DueDate       string                 `protobuf:"bytes,4,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleRisk) Reset() {
	*x = ScheduleRisk{}
	mi := &file_delivery_v1_project_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRisk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRisk) ProtoMessage() {}

func (x *ScheduleRisk) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_project_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRisk.ProtoReflect.Descriptor instead.
func (*ScheduleRisk) Descriptor() ([]byte, []int) {
	return file_delivery_v1_project_proto_rawDescGZIP(), []int{12}
}

func (x *ScheduleRisk) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ScheduleRisk) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ScheduleRisk) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ScheduleRisk) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *ScheduleRisk) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_delivery_v1_project_proto protoreflect.FileDescriptor

const file_delivery_v1_project_proto_rawDesc = "" +
	"\n" +
	"\x19delivery/v1/project.proto\x12\x0fiot.delivery.v1\x1a\x1ayunka/dsl/v1/options.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"M\n" +
	"\x0fProjectResponse\x122\n" +
	"\aproject\x18\x01 \x01(\v2\x18.iot.delivery.v1.ProjectR\aproject:\x06\xd2\xf3\x18\x02\b\x02\"\xf9\x01\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05board\x18\x03 \x01(\tR\x05board\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription:\x06\xd2\xf3\x18\x02\b\x03\"\x80\x01\n" +
	"\x14CreateProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05board\x18\x02 \x01(\tR\x05board\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription:\x06\xd2\xf3\x18\x02\b\x01\"\x1d\n" +
	"\x13ListProjectsRequest:\x06\xd2\xf3\x18\x02\b\x01\"T\n" +
	"\x14ListProjectsResponse\x124\n" +
	"\bprojects\x18\x01 \x03(\v2\x18.iot.delivery.v1.ProjectR\bprojects:\x06\xd2\xf3\x18\x02\b\x02\"B\n" +
	"\x19GetProjectProgressRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId:\x06\xd2\xf3\x18\x02\b\x01\"_\n" +
	"\x17ProjectProgressResponse\x12<\n" +
	"\bprogress\x18\x01 \x01(\v2 .iot.delivery.v1.ProjectProgressR\bprogress:\x06\xd2\xf3\x18\x02\b\x02\"\xfb\x01\n" +
	"\x0fProjectProgress\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vtotal_items\x18\x02 \x01(\x05R\n" +
	"totalItems\x12'\n" +
	"\x0fcompleted_items\x18\x03 \x01(\x05R\x0ecompletedItems\x12!\n" +
	"\ftotal_weight\x18\x04 \x01(\x01R\vtotalWeight\x12)\n" +
	"\x10completed_weight\x18\x05 \x01(\x01R\x0fcompletedWeight\x12)\n" +
	"\x10progress_percent\x18\x06 \x01(\x01R\x0fprogressPercent:\x06\xd2\xf3\x18\x02\b\x03\"B\n" +
	"\x19GetProjectScheduleRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId:\x06\xd2\xf3\x18\x02\b\x01\"_\n" +
	"\x17ProjectScheduleResponse\x12<\n" +
	"\bschedule\x18\x01 \x01(\v2 .iot.delivery.v1.ProjectScheduleR\bschedule:\x06\xd2\xf3\x18\x02\b\x02\"\xc2\x03\n" +
	"\x0fProjectSchedule\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1c\n" +
	"\n" +
	"as_of_date\x18\x02 \x01(\tR\basOfDate\x12\x1f\n" +
	"\vtotal_items\x18\x03 \x01(\x05R\n" +
	"totalItems\x12'\n" +
	"\x0fscheduled_items\x18\x04 \x01(\x05R\x0escheduledItems\x12+\n" +
	"\x11unscheduled_items\x18\x05 \x01(\x05R\x10unscheduledItems\x12#\n" +
	"\rblocked_items\x18\x06 \x01(\x05R\fblockedItems\x12#\n" +
	"\roverdue_items\x18\a \x01(\x05R\foverdueItems\x128\n" +
	"\x18dependency_blocked_items\x18\b \x01(\x05R\x16dependencyBlockedItems\x12:\n" +
	"\bcapacity\x18\t \x03(\v2\x1e.iot.delivery.v1.OwnerCapacityR\bcapacity\x123\n" +
	"\x05risks\x18\n" +
	" \x03(\v2\x1d.iot.delivery.v1.ScheduleRiskR\x05risks:\x06\xd2\xf3\x18\x02\b\x03\"\xc2\x02\n" +
	"\rOwnerCapacity\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x1d\n" +
	"\n" +
	"item_count\x18\x02 \x01(\x05R\titemCount\x12#\n" +
	"\rblocked_items\x18\x03 \x01(\x05R\fblockedItems\x12#\n" +
	"\roverdue_items\x18\x04 \x01(\x05R\foverdueItems\x122\n" +
	"\x15total_estimate_points\x18\x05 \x01(\x01R\x13totalEstimatePoints\x12:\n" +
	"\x19completed_estimate_points\x18\x06 \x01(\x01R\x17completedEstimatePoints\x12:\n" +
	"\x19remaining_estimate_points\x18\a \x01(\x01R\x17remainingEstimatePoints:\x06\xd2\xf3\x18\x02\b\x03\"\x8e\x01\n" +
	"\fScheduleRisk\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x19\n" +
	"\bdue_date\x18\x04 \x01(\tR\adueDate\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason:\x06\xd2\xf3\x18\x02\b\x03BXZVgithub.com/hvritual/iot-delivery-system/backend-yunka/contracts/delivery/v1;deliveryv1b\x06proto3"

var (
	file_delivery_v1_project_proto_rawDescOnce sync.Once
	file_delivery_v1_project_proto_rawDescData []byte
)

func file_delivery_v1_project_proto_rawDescGZIP() []byte {
	file_delivery_v1_project_proto_rawDescOnce.Do(func() {
		file_delivery_v1_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delivery_v1_project_proto_rawDesc), len(file_delivery_v1_project_proto_rawDesc)))
	})
	return file_delivery_v1_project_proto_rawDescData
}

var file_delivery_v1_project_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_delivery_v1_project_proto_goTypes = []any{
	(*ProjectResponse)(nil),           // 0: iot.delivery.v1.ProjectResponse
	(*Project)(nil),                   // 1: iot.delivery.v1.Project
	(*CreateProjectRequest)(nil),      // 2: iot.delivery.v1.CreateProjectRequest
	(*ListProjectsRequest)(nil),       // 3: iot.delivery.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil),      // 4: iot.delivery.v1.ListProjectsResponse
	(*GetProjectProgressRequest)(nil), // 5: iot.delivery.v1.GetProjectProgressRequest
	(*ProjectProgressResponse)(nil),   // 6: iot.delivery.v1.ProjectProgressResponse
	(*ProjectProgress)(nil),           // 7: iot.delivery.v1.ProjectProgress
	(*GetProjectScheduleRequest)(nil), // 8: iot.delivery.v1.GetProjectScheduleRequest
	(*ProjectScheduleResponse)(nil),   // 9: iot.delivery.v1.ProjectScheduleResponse
	(*ProjectSchedule)(nil),           // 10: iot.delivery.v1.ProjectSchedule
	(*OwnerCapacity)(nil),             // 11: iot.delivery.v1.OwnerCapacity
	(*ScheduleRisk)(nil),              // 12: iot.delivery.v1.ScheduleRisk
	(*timestamppb.Timestamp)(nil),     // 13: google.protobuf.Timestamp
}
var file_delivery_v1_project_proto_depIdxs = []int32{
	1,  // 0: iot.delivery.v1.ProjectResponse.project:type_name -> iot.delivery.v1.Project
	13, // 1: iot.delivery.v1.Project.created_at:type_name -> google.protobuf.Timestamp
	13, // 2: iot.delivery.v1.Project.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: iot.delivery.v1.ListProjectsResponse.projects:type_name -> iot.delivery.v1.Project
	7,  // 4: iot.delivery.v1.ProjectProgressResponse.progress:type_name -> iot.delivery.v1.ProjectProgress
	10, // 5: iot.delivery.v1.ProjectScheduleResponse.schedule:type_name -> iot.delivery.v1.ProjectSchedule
	11, // 6: iot.delivery.v1.ProjectSchedule.capacity:type_name -> iot.delivery.v1.OwnerCapacity
	12, // 7: iot.delivery.v1.ProjectSchedule.risks:type_name -> iot.delivery.v1.ScheduleRisk
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_delivery_v1_project_proto_init() }
func file_delivery_v1_project_proto_init() {
	if File_delivery_v1_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delivery_v1_project_proto_rawDesc), len(file_delivery_v1_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_delivery_v1_project_proto_goTypes,
		DependencyIndexes: file_delivery_v1_project_proto_depIdxs,
		MessageInfos:      file_delivery_v1_project_proto_msgTypes,
	}.Build()
	File_delivery_v1_project_proto = out.File
	file_delivery_v1_project_proto_goTypes = nil
	file_delivery_v1_project_proto_depIdxs = nil
}
