// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: delivery/v1/saved_view.proto

package deliveryv1

import (
	_ "github.com/hvritual/yunka.io/pkg/contractdsl/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SavedView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Filter        *WorkItemFilter        `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavedView) Reset() {
	*x = SavedView{}
	mi := &file_delivery_v1_saved_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavedView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavedView) ProtoMessage() {}

func (x *SavedView) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_saved_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavedView.ProtoReflect.Descriptor instead.
func (*SavedView) Descriptor() ([]byte, []int) {
	return file_delivery_v1_saved_view_proto_rawDescGZIP(), []int{0}
}

func (x *SavedView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SavedView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SavedView) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *SavedView) GetFilter() *WorkItemFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SavedView) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SavedView) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type MemberWeek struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        string                 `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	WeekStart     string                 `protobuf:"bytes,2,opt,name=week_start,json=weekStart,proto3" json:"week_start,omitempty"`
	WeekEnd       string                 `protobuf:"bytes,3,opt,name=week_end,json=weekEnd,proto3" json:"week_end,omitempty"`
	Items         []*WorkItem            `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberWeek) Reset() {
	*x = MemberWeek{}
	mi := &file_delivery_v1_saved_view_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberWeek) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberWeek) ProtoMessage() {}

func (x *MemberWeek) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_saved_view_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberWeek.ProtoReflect.Descriptor instead.
func (*MemberWeek) Descriptor() ([]byte, []int) {
	return file_delivery_v1_saved_view_proto_rawDescGZIP(), []int{1}
}

func (x *MemberWeek) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

func (x *MemberWeek) GetWeekStart() string {
	if x != nil {
		return x.WeekStart
	}
	return ""
}

func (x *MemberWeek) GetWeekEnd() string {
	if x != nil {
		return x.WeekEnd
	}
	return ""
}

func (x *MemberWeek) GetItems() []*WorkItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type SaveViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Filter        *WorkItemFilter        `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveViewRequest) Reset() {
	*x = SaveViewRequest{}
	mi := &file_delivery_v1_saved_view_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveViewRequest) ProtoMessage() {}

func (x *SaveViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_saved_view_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveViewRequest.ProtoReflect.Descriptor instead.
func (*SaveViewRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_saved_view_proto_rawDescGZIP(), []int{2}
}

func (x *SaveViewRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveViewRequest) GetFilter() *WorkItemFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListSavedViewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSavedViewsRequest) Reset() {
	*x = ListSavedViewsRequest{}
	mi := &file_delivery_v1_saved_view_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSavedViewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSavedViewsRequest) ProtoMessage() {}

func (x *ListSavedViewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_saved_view_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSavedViewsRequest.ProtoReflect.Descriptor instead.
func (*ListSavedViewsRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_saved_view_proto_rawDescGZIP(), []int{3}
}

type GetMemberWeekRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        string                 `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	WeekStart     string                 `protobuf:"bytes,2,opt,name=week_start,json=weekStart,proto3" json:"week_start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberWeekRequest) Reset() {
	*x = GetMemberWeekRequest{}
	mi := &file_delivery_v1_saved_view_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberWeekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberWeekRequest) ProtoMessage() {}

func (x *GetMemberWeekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_saved_view_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberWeekRequest.ProtoReflect.Descriptor instead.
func (*GetMemberWeekRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_saved_view_proto_rawDescGZIP(), []int{4}
}

func (x *GetMemberWeekRequest) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

func (x *GetMemberWeekRequest) GetWeekStart() string {
	if x != nil {
		return x.WeekStart
	}
	return ""
}

type SavedViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          *SavedView             `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavedViewResponse) Reset() {
	*x = SavedViewResponse{}
	mi := &file_delivery_v1_saved_view_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavedViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavedViewResponse) ProtoMessage() {}

func (x *SavedViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_saved_view_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavedViewResponse.ProtoReflect.Descriptor instead.
func (*SavedViewResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_saved_view_proto_rawDescGZIP(), []int{5}
}

func (x *SavedViewResponse) GetView() *SavedView {
	if x != nil {
		return x.View
	}
	return nil
}

type ListSavedViewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Views         []*SavedView           `protobuf:"bytes,1,rep,name=views,proto3" json:"views,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSavedViewsResponse) Reset() {
	*x = ListSavedViewsResponse{}
	mi := &file_delivery_v1_saved_view_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSavedViewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSavedViewsResponse) ProtoMessage() {}

func (x *ListSavedViewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_saved_view_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSavedViewsResponse.ProtoReflect.Descriptor instead.
func (*ListSavedViewsResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_saved_view_proto_rawDescGZIP(), []int{6}
}

func (x *ListSavedViewsResponse) GetViews() []*SavedView {
	if x != nil {
		return x.Views
	}
	return nil
}

type MemberWeekResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Week          *MemberWeek            `protobuf:"bytes,1,opt,name=week,proto3" json:"week,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberWeekResponse) Reset() {
	*x = MemberWeekResponse{}
	mi := &file_delivery_v1_saved_view_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberWeekResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberWeekResponse) ProtoMessage() {}

func (x *MemberWeekResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_saved_view_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberWeekResponse.ProtoReflect.Descriptor instead.
func (*MemberWeekResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_saved_view_proto_rawDescGZIP(), []int{7}
}

func (x *MemberWeekResponse) GetWeek() *MemberWeek {
	if x != nil {
		return x.Week
	}
	return nil
}

var File_delivery_v1_saved_view_proto protoreflect.FileDescriptor

const file_delivery_v1_saved_view_proto_rawDesc = "" +
	"\n" +
	"\x1cdelivery/v1/saved_view.proto\x12\x0fiot.delivery.v1\x1a\x1ayunka/dsl/v1/options.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bdelivery/v1/work_item.proto\"\xfc\x01\n" +
	"\tSavedView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x127\n" +
	"\x06filter\x18\x04 \x01(\v2\x1f.iot.delivery.v1.WorkItemFilterR\x06filter\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt:\x06\xd2\xf3\x18\x02\b\x03\"\x97\x01\n" +
	"\n" +
	"MemberWeek\x12\x16\n" +
	"\x06member\x18\x01 \x01(\tR\x06member\x12\x1d\n" +
	"\n" +
	"week_start\x18\x02 \x01(\tR\tweekStart\x12\x19\n" +
	"\bweek_end\x18\x03 \x01(\tR\aweekEnd\x12/\n" +
	"\x05items\x18\x04 \x03(\v2\x19.iot.delivery.v1.WorkItemR\x05items:\x06\xd2\xf3\x18\x02\b\x03\"f\n" +
	"\x0fSaveViewRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\x06filter\x18\x02 \x01(\v2\x1f.iot.delivery.v1.WorkItemFilterR\x06filter:\x06\xd2\xf3\x18\x02\b\x01\"\x1f\n" +
	"\x15ListSavedViewsRequest:\x06\xd2\xf3\x18\x02\b\x01\"U\n" +
	"\x14GetMemberWeekRequest\x12\x16\n" +
	"\x06member\x18\x01 \x01(\tR\x06member\x12\x1d\n" +
	"\n" +
	"week_start\x18\x02 \x01(\tR\tweekStart:\x06\xd2\xf3\x18\x02\b\x01\"K\n" +
	"\x11SavedViewResponse\x12.\n" +
	"\x04view\x18\x01 \x01(\v2\x1a.iot.delivery.v1.SavedViewR\x04view:\x06\xd2\xf3\x18\x02\b\x02\"R\n" +
	"\x16ListSavedViewsResponse\x120\n" +
	"\x05views\x18\x01 \x03(\v2\x1a.iot.delivery.v1.SavedViewR\x05views:\x06\xd2\xf3\x18\x02\b\x02\"M\n" +
	"\x12MemberWeekResponse\x12/\n" +
	"\x04week\x18\x01 \x01(\v2\x1b.iot.delivery.v1.MemberWeekR\x04week:\x06\xd2\xf3\x18\x02\b\x02BXZVgithub.com/hvritual/iot-delivery-system/backend-yunka/contracts/delivery/v1;deliveryv1b\x06proto3"

var (
	file_delivery_v1_saved_view_proto_rawDescOnce sync.Once
	file_delivery_v1_saved_view_proto_rawDescData []byte
)

func file_delivery_v1_saved_view_proto_rawDescGZIP() []byte {
	file_delivery_v1_saved_view_proto_rawDescOnce.Do(func() {
		file_delivery_v1_saved_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delivery_v1_saved_view_proto_rawDesc), len(file_delivery_v1_saved_view_proto_rawDesc)))
	})
	return file_delivery_v1_saved_view_proto_rawDescData
}

var file_delivery_v1_saved_view_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_delivery_v1_saved_view_proto_goTypes = []any{
	(*SavedView)(nil),              // 0: iot.delivery.v1.SavedView
	(*MemberWeek)(nil),             // 1: iot.delivery.v1.MemberWeek
	(*SaveViewRequest)(nil),        // 2: iot.delivery.v1.SaveViewRequest
	(*ListSavedViewsRequest)(nil),  // 3: iot.delivery.v1.ListSavedViewsRequest
	(*GetMemberWeekRequest)(nil),   // 4: iot.delivery.v1.GetMemberWeekRequest
	(*SavedViewResponse)(nil),      // 5: iot.delivery.v1.SavedViewResponse
	(*ListSavedViewsResponse)(nil), // 6: iot.delivery.v1.ListSavedViewsResponse
	(*MemberWeekResponse)(nil),     // 7: iot.delivery.v1.MemberWeekResponse
	(*WorkItemFilter)(nil),         // 8: iot.delivery.v1.WorkItemFilter
	(*timestamppb.Timestamp)(nil),  // 9: google.protobuf.Timestamp
	(*WorkItem)(nil),               // 10: iot.delivery.v1.WorkItem
}
var file_delivery_v1_saved_view_proto_depIdxs = []int32{
	8,  // 0: iot.delivery.v1.SavedView.filter:type_name -> iot.delivery.v1.WorkItemFilter
	9,  // 1: iot.delivery.v1.SavedView.created_at:type_name -> google.protobuf.Timestamp
	9,  // 2: iot.delivery.v1.SavedView.updated_at:type_name -> google.protobuf.Timestamp
	10, // 3: iot.delivery.v1.MemberWeek.items:type_name -> iot.delivery.v1.WorkItem
	8,  // 4: iot.delivery.v1.SaveViewRequest.filter:type_name -> iot.delivery.v1.WorkItemFilter
	0,  // 5: iot.delivery.v1.SavedViewResponse.view:type_name -> iot.delivery.v1.SavedView
	0,  // 6: iot.delivery.v1.ListSavedViewsResponse.views:type_name -> iot.delivery.v1.SavedView
	1,  // 7: iot.delivery.v1.MemberWeekResponse.week:type_name -> iot.delivery.v1.MemberWeek
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_delivery_v1_saved_view_proto_init() }
func file_delivery_v1_saved_view_proto_init() {
	if File_delivery_v1_saved_view_proto != nil {
		return
	}
	file_delivery_v1_work_item_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delivery_v1_saved_view_proto_rawDesc), len(file_delivery_v1_saved_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_delivery_v1_saved_view_proto_goTypes,
		DependencyIndexes: file_delivery_v1_saved_view_proto_depIdxs,
		MessageInfos:      file_delivery_v1_saved_view_proto_msgTypes,
	}.Build()
	File_delivery_v1_saved_view_proto = out.File
	file_delivery_v1_saved_view_proto_goTypes = nil
	file_delivery_v1_saved_view_proto_depIdxs = nil
}
