// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: delivery/v1/work_item.proto

package deliveryv1

import (
	_ "github.com/hvritual/yunka.io/pkg/contractdsl/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_delivery_v1_work_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_work_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_work_item_proto_rawDescGZIP(), []int{0}
}

type ListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*WorkItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_delivery_v1_work_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_work_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_work_item_proto_rawDescGZIP(), []int{1}
}

func (x *ListItemsResponse) GetItems() []*WorkItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type WorkItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *WorkItem              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkItemResponse) Reset() {
	*x = WorkItemResponse{}
	mi := &file_delivery_v1_work_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkItemResponse) ProtoMessage() {}

func (x *WorkItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_work_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkItemResponse.ProtoReflect.Descriptor instead.
func (*WorkItemResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_work_item_proto_rawDescGZIP(), []int{2}
}

func (x *WorkItemResponse) GetItem() *WorkItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type CommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	Revision      int64                  `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentResponse) Reset() {
	*x = CommentResponse{}
	mi := &file_delivery_v1_work_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentResponse) ProtoMessage() {}

func (x *CommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_work_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentResponse.ProtoReflect.Descriptor instead.
func (*CommentResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_work_item_proto_rawDescGZIP(), []int{3}
}

func (x *CommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *CommentResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type WorkItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Board           string                 `protobuf:"bytes,3,opt,name=board,proto3" json:"board,omitempty"`
	Type            string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Owner           string                 `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	Priority        string                 `protobuf:"bytes,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Gate            string                 `protobuf:"bytes,8,opt,name=gate,proto3" json:"gate,omitempty"`
	DueDate         string                 `protobuf:"bytes,9,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	Plan            string                 `protobuf:"bytes,10,opt,name=plan,proto3" json:"plan,omitempty"`
	Solution        string                 `protobuf:"bytes,11,opt,name=solution,proto3" json:"solution,omitempty"`
	Decisions       []*Decision            `protobuf:"bytes,12,rep,name=decisions,proto3" json:"decisions,omitempty"`
	Evidence        []*Evidence            `protobuf:"bytes,13,rep,name=evidence,proto3" json:"evidence,omitempty"`
	Retrospective   string                 `protobuf:"bytes,14,opt,name=retrospective,proto3" json:"retrospective,omitempty"`
	Blocker         string                 `protobuf:"bytes,15,opt,name=blocker,proto3" json:"blocker,omitempty"`
	IsSample        bool                   `protobuf:"varint,16,opt,name=is_sample,json=isSample,proto3" json:"is_sample,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ProjectId       string                 `protobuf:"bytes,19,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ParentId        string                 `protobuf:"bytes,20,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Kind            string                 `protobuf:"bytes,21,opt,name=kind,proto3" json:"kind,omitempty"`
	Dependencies    []*WorkItemDependency  `protobuf:"bytes,22,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	ReleaseId       string                 `protobuf:"bytes,23,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	SprintId        string                 `protobuf:"bytes,24,opt,name=sprint_id,json=sprintId,proto3" json:"sprint_id,omitempty"`
	MilestoneId     string                 `protobuf:"bytes,25,opt,name=milestone_id,json=milestoneId,proto3" json:"milestone_id,omitempty"`
	StartDate       string                 `protobuf:"bytes,26,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EstimatePoints  float64                `protobuf:"fixed64,27,opt,name=estimate_points,json=estimatePoints,proto3" json:"estimate_points,omitempty"`
	ProgressPercent int32                  `protobuf:"varint,28,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	IotBindings     []*IoTBinding          `protobuf:"bytes,29,rep,name=iot_bindings,json=iotBindings,proto3" json:"iot_bindings,omitempty"`
	TraceLinks      []*TraceLink           `protobuf:"bytes,30,rep,name=trace_links,json=traceLinks,proto3" json:"trace_links,omitempty"`
	Comments        []*Comment             `protobuf:"bytes,31,rep,name=comments,proto3" json:"comments,omitempty"`
	Activities      []*Activity            `protobuf:"bytes,32,rep,name=activities,proto3" json:"activities,omitempty"`
	Revision        int64                  `protobuf:"varint,33,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkItem) Reset() {
	*x = WorkItem{}
	mi := &file_delivery_v1_work_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkItem) ProtoMessage() {}

func (x *WorkItem) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_work_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkItem.ProtoReflect.Descriptor instead.
func (*WorkItem) Descriptor() ([]byte, []int) {
	return file_delivery_v1_work_item_proto_rawDescGZIP(), []int{4}
}

func (x *WorkItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WorkItem) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *WorkItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WorkItem) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *WorkItem) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *WorkItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkItem) GetGate() string {
	if x != nil {
		return x.Gate
	}
	return ""
}

func (x *WorkItem) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *WorkItem) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *WorkItem) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *WorkItem) GetDecisions() []*Decision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

func (x *WorkItem) GetEvidence() []*Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *WorkItem) GetRetrospective() string {
	if x != nil {
		return x.Retrospective
	}
	return ""
}

func (x *WorkItem) GetBlocker() string {
	if x != nil {
		return x.Blocker
	}
	return ""
}

func (x *WorkItem) GetIsSample() bool {
	if x != nil {
		return x.IsSample
	}
	return false
}

func (x *WorkItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WorkItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *WorkItem) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *WorkItem) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *WorkItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WorkItem) GetDependencies() []*WorkItemDependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *WorkItem) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *WorkItem) GetSprintId() string {
	if x != nil {
		return x.SprintId
	}
	return ""
}

func (x *WorkItem) GetMilestoneId() string {
	if x != nil {
		return x.MilestoneId
	}
	return ""
}

func (x *WorkItem) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *WorkItem) GetEstimatePoints() float64 {
	if x != nil {
		return x.EstimatePoints
	}
	return 0
}

func (x *WorkItem) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *WorkItem) GetIotBindings() []*IoTBinding {
	if x != nil {
		return x.IotBindings
	}
	return nil
}

func (x *WorkItem) GetTraceLinks() []*TraceLink {
	if x != nil {
		return x.TraceLinks
	}
	return nil
}

func (x *WorkItem) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *WorkItem) GetActivities() []*Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *WorkItem) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type CreateItemRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Board           string                 `protobuf:"bytes,2,opt,name=board,proto3" json:"board,omitempty"`
	Type            string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Owner           string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Priority        string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	DueDate         string                 `protobuf:"bytes,6,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	Plan            string                 `protobuf:"bytes,7,opt,name=plan,proto3" json:"plan,omitempty"`
	Solution        string                 `protobuf:"bytes,8,opt,name=solution,proto3" json:"solution,omitempty"`
	IsSample        bool                   `protobuf:"varint,9,opt,name=is_sample,json=isSample,proto3" json:"is_sample,omitempty"`
	ProjectId       string                 `protobuf:"bytes,10,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ParentId        string                 `protobuf:"bytes,11,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Kind            string                 `protobuf:"bytes,12,opt,name=kind,proto3" json:"kind,omitempty"`
	Dependencies    []*WorkItemDependency  `protobuf:"bytes,13,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	ReleaseId       string                 `protobuf:"bytes,14,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	SprintId        string                 `protobuf:"bytes,15,opt,name=sprint_id,json=sprintId,proto3" json:"sprint_id,omitempty"`
	MilestoneId     string                 `protobuf:"bytes,16,opt,name=milestone_id,json=milestoneId,proto3" json:"milestone_id,omitempty"`
	StartDate       string                 `protobuf:"bytes,17,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EstimatePoints  float64                `protobuf:"fixed64,18,opt,name=estimate_points,json=estimatePoints,proto3" json:"estimate_points,omitempty"`
	ProgressPercent int32                  `protobuf:"varint,19,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	IotBindings     []*IoTBinding          `protobuf:"bytes,20,rep,name=iot_bindings,json=iotBindings,proto3" json:"iot_bindings,omitempty"`
	TraceLinks      []*TraceLink           `protobuf:"bytes,21,rep,name=trace_links,json=traceLinks,proto3" json:"trace_links,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_delivery_v1_work_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_work_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_work_item_proto_rawDescGZIP(), []int{5}
}

func (x *CreateItemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateItemRequest) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *CreateItemRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateItemRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CreateItemRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *CreateItemRequest) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *CreateItemRequest) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *CreateItemRequest) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *CreateItemRequest) GetIsSample() bool {
	if x != nil {
		return x.IsSample
	}
	return false
}

func (x *CreateItemRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateItemRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreateItemRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CreateItemRequest) GetDependencies() []*WorkItemDependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *CreateItemRequest) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *CreateItemRequest) GetSprintId() string {
	if x != nil {
		return x.SprintId
	}
	return ""
}

func (x *CreateItemRequest) GetMilestoneId() string {
	if x != nil {
		return x.MilestoneId
	}
	return ""
}

func (x *CreateItemRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateItemRequest) GetEstimatePoints() float64 {
	if x != nil {
		return x.EstimatePoints
	}
	return 0
}

func (x *CreateItemRequest) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *CreateItemRequest) GetIotBindings() []*IoTBinding {
	if x != nil {
		return x.IotBindings
	}
	return nil
}

func (x *CreateItemRequest) GetTraceLinks() []*TraceLink {
	if x != nil {
		return x.TraceLinks
	}
	return nil
}

type UpdateItemRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdateMask       []string               `protobuf:"bytes,2,rep,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Owner            string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Priority         string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	ReleaseId        string                 `protobuf:"bytes,6,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	SprintId         string                 `protobuf:"bytes,7,opt,name=sprint_id,json=sprintId,proto3" json:"sprint_id,omitempty"`
	MilestoneId      string                 `protobuf:"bytes,8,opt,name=milestone_id,json=milestoneId,proto3" json:"milestone_id,omitempty"`
	StartDate        string                 `protobuf:"bytes,9,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	DueDate          string                 `protobuf:"bytes,10,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	EstimatePoints   float64                `protobuf:"fixed64,11,opt,name=estimate_points,json=estimatePoints,proto3" json:"estimate_points,omitempty"`
	ProgressPercent  int32                  `protobuf:"varint,12,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	Dependencies     []*WorkItemDependency  `protobuf:"bytes,13,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	IotBindings      []*IoTBinding          `protobuf:"bytes,14,rep,name=iot_bindings,json=iotBindings,proto3" json:"iot_bindings,omitempty"`
	TraceLinks       []*TraceLink           `protobuf:"bytes,15,rep,name=trace_links,json=traceLinks,proto3" json:"trace_links,omitempty"`
	ExpectedRevision int64                  `protobuf:"varint,16,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_delivery_v1_work_item_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_work_item_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_work_item_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateItemRequest) GetUpdateMask() []string {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateItemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateItemRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *UpdateItemRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *UpdateItemRequest) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *UpdateItemRequest) GetSprintId() string {
	if x != nil {
		return x.SprintId
	}
	return ""
}

func (x *UpdateItemRequest) GetMilestoneId() string {
	if x != nil {
		return x.MilestoneId
	}
	return ""
}

func (x *UpdateItemRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *UpdateItemRequest) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *UpdateItemRequest) GetEstimatePoints() float64 {
	if x != nil {
		return x.EstimatePoints
	}
	return 0
}

func (x *UpdateItemRequest) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *UpdateItemRequest) GetDependencies() []*WorkItemDependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *UpdateItemRequest) GetIotBindings() []*IoTBinding {
	if x != nil {
		return x.IotBindings
	}
	return nil
}

func (x *UpdateItemRequest) GetTraceLinks() []*TraceLink {
	if x != nil {
		return x.TraceLinks
	}
	return nil
}

func (x *UpdateItemRequest) GetExpectedRevision() int64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type CreateItemCommentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Body             string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	ExpectedRevision int64                  `protobuf:"varint,3,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateItemCommentRequest) Reset() {
	*x = CreateItemCommentRequest{}
	mi := &file_delivery_v1_work_item_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemCommentRequest) ProtoMessage() {}

func (x *CreateItemCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_work_item_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateItemCommentRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_work_item_proto_rawDescGZIP(), []int{7}
}

func (x *CreateItemCommentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateItemCommentRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CreateItemCommentRequest) GetExpectedRevision() int64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type UpdateItemContextRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Plan             *string                `protobuf:"bytes,2,opt,name=plan,proto3,oneof" json:"plan,omitempty"`
	Solution         *string                `protobuf:"bytes,3,opt,name=solution,proto3,oneof" json:"solution,omitempty"`
	Blocker          *string                `protobuf:"bytes,4,opt,name=blocker,proto3,oneof" json:"blocker,omitempty"`
	Decision         *Decision              `protobuf:"bytes,5,opt,name=decision,proto3,oneof" json:"decision,omitempty"`
	ExpectedRevision int64                  `protobuf:"varint,6,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateItemContextRequest) Reset() {
	*x = UpdateItemContextRequest{}
	mi := &file_delivery_v1_work_item_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemContextRequest) ProtoMessage() {}

func (x *UpdateItemContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_work_item_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemContextRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemContextRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_work_item_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateItemContextRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateItemContextRequest) GetPlan() string {
	if x != nil && x.Plan != nil {
		return *x.Plan
	}
	return ""
}

func (x *UpdateItemContextRequest) GetSolution() string {
	if x != nil && x.Solution != nil {
		return *x.Solution
	}
	return ""
}

func (x *UpdateItemContextRequest) GetBlocker() string {
	if x != nil && x.Blocker != nil {
		return *x.Blocker
	}
	return ""
}

func (x *UpdateItemContextRequest) GetDecision() *Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}

func (x *UpdateItemContextRequest) GetExpectedRevision() int64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type AdvanceGateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Gate             string                 `protobuf:"bytes,2,opt,name=gate,proto3" json:"gate,omitempty"`
	Evidence         []*Evidence            `protobuf:"bytes,3,rep,name=evidence,proto3" json:"evidence,omitempty"`
	ExpectedRevision int64                  `protobuf:"varint,4,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AdvanceGateRequest) Reset() {
	*x = AdvanceGateRequest{}
	mi := &file_delivery_v1_work_item_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvanceGateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvanceGateRequest) ProtoMessage() {}

func (x *AdvanceGateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_work_item_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvanceGateRequest.ProtoReflect.Descriptor instead.
func (*AdvanceGateRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_work_item_proto_rawDescGZIP(), []int{9}
}

func (x *AdvanceGateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdvanceGateRequest) GetGate() string {
	if x != nil {
		return x.Gate
	}
	return ""
}

func (x *AdvanceGateRequest) GetEvidence() []*Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *AdvanceGateRequest) GetExpectedRevision() int64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type CloseItemRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Retrospective    string                 `protobuf:"bytes,2,opt,name=retrospective,proto3" json:"retrospective,omitempty"`
	ExpectedRevision int64                  `protobuf:"varint,3,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CloseItemRequest) Reset() {
	*x = CloseItemRequest{}
	mi := &file_delivery_v1_work_item_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseItemRequest) ProtoMessage() {}

func (x *CloseItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_work_item_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseItemRequest.ProtoReflect.Descriptor instead.
func (*CloseItemRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_work_item_proto_rawDescGZIP(), []int{10}
}

func (x *CloseItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CloseItemRequest) GetRetrospective() string {
	if x != nil {
		return x.Retrospective
	}
	return ""
}

func (x *CloseItemRequest) GetExpectedRevision() int64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type WorkItemFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Board         string                 `protobuf:"bytes,2,opt,name=board,proto3" json:"board,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Kind          string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	ReleaseId     string                 `protobuf:"bytes,6,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	SprintId      string                 `protobuf:"bytes,7,opt,name=sprint_id,json=sprintId,proto3" json:"sprint_id,omitempty"`
	MilestoneId   string                 `protobuf:"bytes,8,opt,name=milestone_id,json=milestoneId,proto3" json:"milestone_id,omitempty"`
	Query         string                 `protobuf:"bytes,9,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkItemFilter) Reset() {
	*x = WorkItemFilter{}
	mi := &file_delivery_v1_work_item_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkItemFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkItemFilter) ProtoMessage() {}

func (x *WorkItemFilter) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_work_item_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkItemFilter.ProtoReflect.Descriptor instead.
func (*WorkItemFilter) Descriptor() ([]byte, []int) {
	return file_delivery_v1_work_item_proto_rawDescGZIP(), []int{11}
}

func (x *WorkItemFilter) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *WorkItemFilter) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *WorkItemFilter) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *WorkItemFilter) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkItemFilter) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WorkItemFilter) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *WorkItemFilter) GetSprintId() string {
	if x != nil {
		return x.SprintId
	}
	return ""
}

func (x *WorkItemFilter) GetMilestoneId() string {
	if x != nil {
		return x.MilestoneId
	}
	return ""
}

func (x *WorkItemFilter) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_delivery_v1_work_item_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_work_item_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_work_item_proto_rawDescGZIP(), []int{12}
}

func (x *GetItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SearchItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Board         string                 `protobuf:"bytes,2,opt,name=board,proto3" json:"board,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Kind          string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	ReleaseId     string                 `protobuf:"bytes,6,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	SprintId      string                 `protobuf:"bytes,7,opt,name=sprint_id,json=sprintId,proto3" json:"sprint_id,omitempty"`
	MilestoneId   string                 `protobuf:"bytes,8,opt,name=milestone_id,json=milestoneId,proto3" json:"milestone_id,omitempty"`
	Query         string                 `protobuf:"bytes,9,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchItemsRequest) Reset() {
	*x = SearchItemsRequest{}
	mi := &file_delivery_v1_work_item_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchItemsRequest) ProtoMessage() {}

func (x *SearchItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_work_item_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchItemsRequest.ProtoReflect.Descriptor instead.
func (*SearchItemsRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_work_item_proto_rawDescGZIP(), []int{13}
}

func (x *SearchItemsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SearchItemsRequest) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *SearchItemsRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *SearchItemsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SearchItemsRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SearchItemsRequest) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *SearchItemsRequest) GetSprintId() string {
	if x != nil {
		return x.SprintId
	}
	return ""
}

func (x *SearchItemsRequest) GetMilestoneId() string {
	if x != nil {
		return x.MilestoneId
	}
	return ""
}

func (x *SearchItemsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*WorkItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchItemsResponse) Reset() {
	*x = SearchItemsResponse{}
	mi := &file_delivery_v1_work_item_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchItemsResponse) ProtoMessage() {}

func (x *SearchItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_work_item_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchItemsResponse.ProtoReflect.Descriptor instead.
func (*SearchItemsResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_work_item_proto_rawDescGZIP(), []int{14}
}

func (x *SearchItemsResponse) GetItems() []*WorkItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type FindSimilarItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Board         string                 `protobuf:"bytes,2,opt,name=board,proto3" json:"board,omitempty"`
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSimilarItemsRequest) Reset() {
	*x = FindSimilarItemsRequest{}
	mi := &file_delivery_v1_work_item_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSimilarItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSimilarItemsRequest) ProtoMessage() {}

func (x *FindSimilarItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_work_item_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSimilarItemsRequest.ProtoReflect.Descriptor instead.
func (*FindSimilarItemsRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_work_item_proto_rawDescGZIP(), []int{15}
}

func (x *FindSimilarItemsRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FindSimilarItemsRequest) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *FindSimilarItemsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *FindSimilarItemsRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *FindSimilarItemsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FindSimilarItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    []*SimilarityCandidate `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindSimilarItemsResponse) Reset() {
	*x = FindSimilarItemsResponse{}
	mi := &file_delivery_v1_work_item_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindSimilarItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSimilarItemsResponse) ProtoMessage() {}

func (x *FindSimilarItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_work_item_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSimilarItemsResponse.ProtoReflect.Descriptor instead.
func (*FindSimilarItemsResponse) Descriptor() ([]byte, []int) {
	return file_delivery_v1_work_item_proto_rawDescGZIP(), []int{16}
}

func (x *FindSimilarItemsResponse) GetCandidates() []*SimilarityCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type SimilarityCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *WorkItem              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Exact         bool                   `protobuf:"varint,3,opt,name=exact,proto3" json:"exact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimilarityCandidate) Reset() {
	*x = SimilarityCandidate{}
	mi := &file_delivery_v1_work_item_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarityCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarityCandidate) ProtoMessage() {}

func (x *SimilarityCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_work_item_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarityCandidate.ProtoReflect.Descriptor instead.
func (*SimilarityCandidate) Descriptor() ([]byte, []int) {
	return file_delivery_v1_work_item_proto_rawDescGZIP(), []int{17}
}

func (x *SimilarityCandidate) GetItem() *WorkItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *SimilarityCandidate) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SimilarityCandidate) GetExact() bool {
	if x != nil {
		return x.Exact
	}
	return false
}

var File_delivery_v1_work_item_proto protoreflect.FileDescriptor

const file_delivery_v1_work_item_proto_rawDesc = "" +
	"\n" +
	"\x1bdelivery/v1/work_item.proto\x12\x0fiot.delivery.v1\x1a\x1ayunka/dsl/v1/options.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18delivery/v1/common.proto\"\x1a\n" +
	"\x10ListItemsRequest:\x06\xd2\xf3\x18\x02\b\x01\"L\n" +
	"\x11ListItemsResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.iot.delivery.v1.WorkItemR\x05items:\x06\xd2\xf3\x18\x02\b\x02\"I\n" +
	"\x10WorkItemResponse\x12-\n" +
	"\x04item\x18\x01 \x01(\v2\x19.iot.delivery.v1.WorkItemR\x04item:\x06\xd2\xf3\x18\x02\b\x02\"i\n" +
	"\x0fCommentResponse\x122\n" +
	"\acomment\x18\x01 \x01(\v2\x18.iot.delivery.v1.CommentR\acomment\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x03R\brevision:\x06\xd2\xf3\x18\x02\b\x02\"\xc3\t\n" +
	"\bWorkItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05board\x18\x03 \x01(\tR\x05board\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05owner\x18\x05 \x01(\tR\x05owner\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\tR\bpriority\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x12\n" +
	"\x04gate\x18\b \x01(\tR\x04gate\x12\x19\n" +
	"\bdue_date\x18\t \x01(\tR\adueDate\x12\x12\n" +
	"\x04plan\x18\n" +
	" \x01(\tR\x04plan\x12\x1a\n" +
	"\bsolution\x18\v \x01(\tR\bsolution\x127\n" +
	"\tdecisions\x18\f \x03(\v2\x19.iot.delivery.v1.DecisionR\tdecisions\x125\n" +
	"\bevidence\x18\r \x03(\v2\x19.iot.delivery.v1.EvidenceR\bevidence\x12$\n" +
	"\rretrospective\x18\x0e \x01(\tR\rretrospective\x12\x18\n" +
	"\ablocker\x18\x0f \x01(\tR\ablocker\x12\x1b\n" +
	"\tis_sample\x18\x10 \x01(\bR\bisSample\x129\n" +
	"\n" +
	"created_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"project_id\x18\x13 \x01(\tR\tprojectId\x12\x1b\n" +
	"\tparent_id\x18\x14 \x01(\tR\bparentId\x12\x12\n" +
	"\x04kind\x18\x15 \x01(\tR\x04kind\x12G\n" +
	"\fdependencies\x18\x16 \x03(\v2#.iot.delivery.v1.WorkItemDependencyR\fdependencies\x12\x1d\n" +
	"\n" +
	"release_id\x18\x17 \x01(\tR\treleaseId\x12\x1b\n" +
	"\tsprint_id\x18\x18 \x01(\tR\bsprintId\x12!\n" +
	"\fmilestone_id\x18\x19 \x01(\tR\vmilestoneId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x1a \x01(\tR\tstartDate\x12'\n" +
	"\x0festimate_points\x18\x1b \x01(\x01R\x0eestimatePoints\x12)\n" +
	"\x10progress_percent\x18\x1c \x01(\x05R\x0fprogressPercent\x12>\n" +
	"\fiot_bindings\x18\x1d \x03(\v2\x1b.iot.delivery.v1.IoTBindingR\viotBindings\x12;\n" +
	"\vtrace_links\x18\x1e \x03(\v2\x1a.iot.delivery.v1.TraceLinkR\n" +
	"traceLinks\x124\n" +
	"\bcomments\x18\x1f \x03(\v2\x18.iot.delivery.v1.CommentR\bcomments\x129\n" +
	"\n" +
	"activities\x18  \x03(\v2\x19.iot.delivery.v1.ActivityR\n" +
	"activities\x12\x1a\n" +
	"\brevision\x18! \x01(\x03R\brevision:\x06\xd2\xf3\x18\x02\b\x03\"\xdd\x05\n" +
	"\x11CreateItemRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05board\x18\x02 \x01(\tR\x05board\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x12\x19\n" +
	"\bdue_date\x18\x06 \x01(\tR\adueDate\x12\x12\n" +
	"\x04plan\x18\a \x01(\tR\x04plan\x12\x1a\n" +
	"\bsolution\x18\b \x01(\tR\bsolution\x12\x1b\n" +
	"\tis_sample\x18\t \x01(\bR\bisSample\x12\x1d\n" +
	"\n" +
	"project_id\x18\n" +
	" \x01(\tR\tprojectId\x12\x1b\n" +
	"\tparent_id\x18\v \x01(\tR\bparentId\x12\x12\n" +
	"\x04kind\x18\f \x01(\tR\x04kind\x12G\n" +
	"\fdependencies\x18\r \x03(\v2#.iot.delivery.v1.WorkItemDependencyR\fdependencies\x12\x1d\n" +
	"\n" +
	"release_id\x18\x0e \x01(\tR\treleaseId\x12\x1b\n" +
	"\tsprint_id\x18\x0f \x01(\tR\bsprintId\x12!\n" +
	"\fmilestone_id\x18\x10 \x01(\tR\vmilestoneId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x11 \x01(\tR\tstartDate\x12'\n" +
	"\x0festimate_points\x18\x12 \x01(\x01R\x0eestimatePoints\x12)\n" +
	"\x10progress_percent\x18\x13 \x01(\x05R\x0fprogressPercent\x12>\n" +
	"\fiot_bindings\x18\x14 \x03(\v2\x1b.iot.delivery.v1.IoTBindingR\viotBindings\x12;\n" +
	"\vtrace_links\x18\x15 \x03(\v2\x1a.iot.delivery.v1.TraceLinkR\n" +
	"traceLinks:\x06\xd2\xf3\x18\x02\b\x01\"\xf4\x04\n" +
	"\x11UpdateItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vupdate_mask\x18\x02 \x03(\tR\n" +
	"updateMask\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x12\x1d\n" +
	"\n" +
	"release_id\x18\x06 \x01(\tR\treleaseId\x12\x1b\n" +
	"\tsprint_id\x18\a \x01(\tR\bsprintId\x12!\n" +
	"\fmilestone_id\x18\b \x01(\tR\vmilestoneId\x12\x1d\n" +
	"\n" +
	"start_date\x18\t \x01(\tR\tstartDate\x12\x19\n" +
	"\bdue_date\x18\n" +
	" \x01(\tR\adueDate\x12'\n" +
	"\x0festimate_points\x18\v \x01(\x01R\x0eestimatePoints\x12)\n" +
	"\x10progress_percent\x18\f \x01(\x05R\x0fprogressPercent\x12G\n" +
	"\fdependencies\x18\r \x03(\v2#.iot.delivery.v1.WorkItemDependencyR\fdependencies\x12>\n" +
	"\fiot_bindings\x18\x0e \x03(\v2\x1b.iot.delivery.v1.IoTBindingR\viotBindings\x12;\n" +
	"\vtrace_links\x18\x0f \x03(\v2\x1a.iot.delivery.v1.TraceLinkR\n" +
	"traceLinks\x12+\n" +
	"\x11expected_revision\x18\x10 \x01(\x03R\x10expectedRevision:\x06\xd2\xf3\x18\x02\b\x01\"s\n" +
	"\x18CreateItemCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12+\n" +
	"\x11expected_revision\x18\x03 \x01(\x03R\x10expectedRevision:\x06\xd2\xf3\x18\x02\b\x01\"\xa3\x02\n" +
	"\x18UpdateItemContextRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04plan\x18\x02 \x01(\tH\x00R\x04plan\x88\x01\x01\x12\x1f\n" +
	"\bsolution\x18\x03 \x01(\tH\x01R\bsolution\x88\x01\x01\x12\x1d\n" +
	"\ablocker\x18\x04 \x01(\tH\x02R\ablocker\x88\x01\x01\x12:\n" +
	"\bdecision\x18\x05 \x01(\v2\x19.iot.delivery.v1.DecisionH\x03R\bdecision\x88\x01\x01\x12+\n" +
	"\x11expected_revision\x18\x06 \x01(\x03R\x10expectedRevision:\x06\xd2\xf3\x18\x02\b\x01B\a\n" +
	"\x05_planB\v\n" +
	"\t_solutionB\n" +
	"\n" +
	"\b_blockerB\v\n" +
	"\t_decision\"\xa4\x01\n" +
	"\x12AdvanceGateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04gate\x18\x02 \x01(\tR\x04gate\x125\n" +
	"\bevidence\x18\x03 \x03(\v2\x19.iot.delivery.v1.EvidenceR\bevidence\x12+\n" +
	"\x11expected_revision\x18\x04 \x01(\x03R\x10expectedRevision:\x06\xd2\xf3\x18\x02\b\x01\"}\n" +
	"\x10CloseItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\rretrospective\x18\x02 \x01(\tR\rretrospective\x12+\n" +
	"\x11expected_revision\x18\x03 \x01(\x03R\x10expectedRevision:\x06\xd2\xf3\x18\x02\b\x01\"\x84\x02\n" +
	"\x0eWorkItemFilter\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x14\n" +
	"\x05board\x18\x02 \x01(\tR\x05board\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"release_id\x18\x06 \x01(\tR\treleaseId\x12\x1b\n" +
	"\tsprint_id\x18\a \x01(\tR\bsprintId\x12!\n" +
	"\fmilestone_id\x18\b \x01(\tR\vmilestoneId\x12\x14\n" +
	"\x05query\x18\t \x01(\tR\x05query:\x06\xd2\xf3\x18\x02\b\x03\"(\n" +
	"\x0eGetItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id:\x06\xd2\xf3\x18\x02\b\x01\"\x88\x02\n" +
	"\x12SearchItemsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x14\n" +
	"\x05board\x18\x02 \x01(\tR\x05board\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"release_id\x18\x06 \x01(\tR\treleaseId\x12\x1b\n" +
	"\tsprint_id\x18\a \x01(\tR\bsprintId\x12!\n" +
	"\fmilestone_id\x18\b \x01(\tR\vmilestoneId\x12\x14\n" +
	"\x05query\x18\t \x01(\tR\x05query:\x06\xd2\xf3\x18\x02\b\x01\"N\n" +
	"\x13SearchItemsResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.iot.delivery.v1.WorkItemR\x05items:\x06\xd2\xf3\x18\x02\b\x02\"\x96\x01\n" +
	"\x17FindSimilarItemsRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05board\x18\x02 \x01(\tR\x05board\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit:\x06\xd2\xf3\x18\x02\b\x01\"h\n" +
	"\x18FindSimilarItemsResponse\x12D\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2$.iot.delivery.v1.SimilarityCandidateR\n" +
	"candidates:\x06\xd2\xf3\x18\x02\b\x02\"x\n" +
	"\x13SimilarityCandidate\x12-\n" +
	"\x04item\x18\x01 \x01(\v2\x19.iot.delivery.v1.WorkItemR\x04item\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x14\n" +
	"\x05exact\x18\x03 \x01(\bR\x05exact:\x06\xd2\xf3\x18\x02\b\x03BXZVgithub.com/hvritual/iot-delivery-system/backend-yunka/contracts/delivery/v1;deliveryv1b\x06proto3"

var (
	file_delivery_v1_work_item_proto_rawDescOnce sync.Once
	file_delivery_v1_work_item_proto_rawDescData []byte
)

func file_delivery_v1_work_item_proto_rawDescGZIP() []byte {
	file_delivery_v1_work_item_proto_rawDescOnce.Do(func() {
		file_delivery_v1_work_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delivery_v1_work_item_proto_rawDesc), len(file_delivery_v1_work_item_proto_rawDesc)))
	})
	return file_delivery_v1_work_item_proto_rawDescData
}

var file_delivery_v1_work_item_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_delivery_v1_work_item_proto_goTypes = []any{
	(*ListItemsRequest)(nil),         // 0: iot.delivery.v1.ListItemsRequest
	(*ListItemsResponse)(nil),        // 1: iot.delivery.v1.ListItemsResponse
	(*WorkItemResponse)(nil),         // 2: iot.delivery.v1.WorkItemResponse
	(*CommentResponse)(nil),          // 3: iot.delivery.v1.CommentResponse
	(*WorkItem)(nil),                 // 4: iot.delivery.v1.WorkItem
	(*CreateItemRequest)(nil),        // 5: iot.delivery.v1.CreateItemRequest
	(*UpdateItemRequest)(nil),        // 6: iot.delivery.v1.UpdateItemRequest
	(*CreateItemCommentRequest)(nil), // 7: iot.delivery.v1.CreateItemCommentRequest
	(*UpdateItemContextRequest)(nil), // 8: iot.delivery.v1.UpdateItemContextRequest
	(*AdvanceGateRequest)(nil),       // 9: iot.delivery.v1.AdvanceGateRequest
	(*CloseItemRequest)(nil),         // 10: iot.delivery.v1.CloseItemRequest
	(*WorkItemFilter)(nil),           // 11: iot.delivery.v1.WorkItemFilter
	(*GetItemRequest)(nil),           // 12: iot.delivery.v1.GetItemRequest
	(*SearchItemsRequest)(nil),       // 13: iot.delivery.v1.SearchItemsRequest
	(*SearchItemsResponse)(nil),      // 14: iot.delivery.v1.SearchItemsResponse
	(*FindSimilarItemsRequest)(nil),  // 15: iot.delivery.v1.FindSimilarItemsRequest
	(*FindSimilarItemsResponse)(nil), // 16: iot.delivery.v1.FindSimilarItemsResponse
	(*SimilarityCandidate)(nil),      // 17: iot.delivery.v1.SimilarityCandidate
	(*Comment)(nil),                  // 18: iot.delivery.v1.Comment
	(*Decision)(nil),                 // 19: iot.delivery.v1.Decision
	(*Evidence)(nil),                 // 20: iot.delivery.v1.Evidence
	(*timestamppb.Timestamp)(nil),    // 21: google.protobuf.Timestamp
	(*WorkItemDependency)(nil),       // 22: iot.delivery.v1.WorkItemDependency
	(*IoTBinding)(nil),               // 23: iot.delivery.v1.IoTBinding
	(*TraceLink)(nil),                // 24: iot.delivery.v1.TraceLink
	(*Activity)(nil),                 // 25: iot.delivery.v1.Activity
}
var file_delivery_v1_work_item_proto_depIdxs = []int32{
	4,  // 0: iot.delivery.v1.ListItemsResponse.items:type_name -> iot.delivery.v1.WorkItem
	4,  // 1: iot.delivery.v1.WorkItemResponse.item:type_name -> iot.delivery.v1.WorkItem
	18, // 2: iot.delivery.v1.CommentResponse.comment:type_name -> iot.delivery.v1.Comment
	19, // 3: iot.delivery.v1.WorkItem.decisions:type_name -> iot.delivery.v1.Decision
	20, // 4: iot.delivery.v1.WorkItem.evidence:type_name -> iot.delivery.v1.Evidence
	21, // 5: iot.delivery.v1.WorkItem.created_at:type_name -> google.protobuf.Timestamp
	21, // 6: iot.delivery.v1.WorkItem.updated_at:type_name -> google.protobuf.Timestamp
	22, // 7: iot.delivery.v1.WorkItem.dependencies:type_name -> iot.delivery.v1.WorkItemDependency
	23, // 8: iot.delivery.v1.WorkItem.iot_bindings:type_name -> iot.delivery.v1.IoTBinding
	24, // 9: iot.delivery.v1.WorkItem.trace_links:type_name -> iot.delivery.v1.TraceLink
	18, // 10: iot.delivery.v1.WorkItem.comments:type_name -> iot.delivery.v1.Comment
	25, // 11: iot.delivery.v1.WorkItem.activities:type_name -> iot.delivery.v1.Activity
	22, // 12: iot.delivery.v1.CreateItemRequest.dependencies:type_name -> iot.delivery.v1.WorkItemDependency
	23, // 13: iot.delivery.v1.CreateItemRequest.iot_bindings:type_name -> iot.delivery.v1.IoTBinding
	24, // 14: iot.delivery.v1.CreateItemRequest.trace_links:type_name -> iot.delivery.v1.TraceLink
	22, // 15: iot.delivery.v1.UpdateItemRequest.dependencies:type_name -> iot.delivery.v1.WorkItemDependency
	23, // 16: iot.delivery.v1.UpdateItemRequest.iot_bindings:type_name -> iot.delivery.v1.IoTBinding
	24, // 17: iot.delivery.v1.UpdateItemRequest.trace_links:type_name -> iot.delivery.v1.TraceLink
	19, // 18: iot.delivery.v1.UpdateItemContextRequest.decision:type_name -> iot.delivery.v1.Decision
	20, // 19: iot.delivery.v1.AdvanceGateRequest.evidence:type_name -> iot.delivery.v1.Evidence
	4,  // 20: iot.delivery.v1.SearchItemsResponse.items:type_name -> iot.delivery.v1.WorkItem
	17, // 21: iot.delivery.v1.FindSimilarItemsResponse.candidates:type_name -> iot.delivery.v1.SimilarityCandidate
	4,  // 22: iot.delivery.v1.SimilarityCandidate.item:type_name -> iot.delivery.v1.WorkItem
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_delivery_v1_work_item_proto_init() }
func file_delivery_v1_work_item_proto_init() {
	if File_delivery_v1_work_item_proto != nil {
		return
	}
	file_delivery_v1_common_proto_init()
	file_delivery_v1_work_item_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delivery_v1_work_item_proto_rawDesc), len(file_delivery_v1_work_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_delivery_v1_work_item_proto_goTypes,
		DependencyIndexes: file_delivery_v1_work_item_proto_depIdxs,
		MessageInfos:      file_delivery_v1_work_item_proto_msgTypes,
	}.Build()
	File_delivery_v1_work_item_proto = out.File
	file_delivery_v1_work_item_proto_goTypes = nil
	file_delivery_v1_work_item_proto_depIdxs = nil
}
