// Code generated by yunka module; DO NOT EDIT.

package delivery

import (
	"github.com/hvritual/yunka.io/framework/core/modulecatalog"
)

func GeneratedDescriptor() modulecatalog.Descriptor {
	return modulecatalog.Descriptor{
		Name:         ModuleName,
		Version:      "v0.1.0",
		Requirements: modulecatalog.Requirements{},
		Build:        generatedBuild,
	}
}

func generatedBuild(context modulecatalog.BuildContext) (modulecatalog.Instance, error) {
	dependencies := Dependencies{}
	return NewModule(dependencies)
}
