// Code generated by yunka contract; DO NOT EDIT.

package application

import (
	"context"
	deliveryv1 "github.com/hvritual/iot-delivery-system/backend-yunka/contracts/delivery/v1"
)

// DeliveryService is generated from PB and contains no business implementation.
type DeliveryService interface {
	AdvanceGate(context.Context, *deliveryv1.AdvanceGateRequest) (*deliveryv1.WorkItemResponse, error)
	CloseItem(context.Context, *deliveryv1.CloseItemRequest) (*deliveryv1.WorkItemResponse, error)
	CreateItem(context.Context, *deliveryv1.CreateItemRequest) (*deliveryv1.WorkItemResponse, error)
	GetDashboard(context.Context, *deliveryv1.GetDashboardRequest) (*deliveryv1.GetDashboardResponse, error)
	ListItems(context.Context, *deliveryv1.ListItemsRequest) (*deliveryv1.ListItemsResponse, error)
	UpdateItemContext(context.Context, *deliveryv1.UpdateItemContextRequest) (*deliveryv1.WorkItemResponse, error)
}
